import crypto from 'node:crypto';
import { readJson,updateJson } from '@/lib/storage';
import { gradeFromPercent } from '@/lib/grading';
import { rewardGradedAssessment } from '@/services/assessmentRewards';
import { notifyStudent,notifyAssignmentStudents } from '@/services/notifications';

export async function getSummativeEvents(assignmentId){return (await readJson('summativeAssessments',[])).filter(x=>x.assignmentId===assignmentId).sort((a,b)=>new Date(a.date)-new Date(b.date));}
export async function createSummative(input,user){const item={id:`summative_${crypto.randomUUID()}`,assignmentId:input.assignmentId,title:input.title.trim(),date:input.date,description:(input.description||'').trim(),criteria:input.criteria,createdBy:user.id,createdAt:new Date().toISOString(),results:[]};await updateJson('summativeAssessments',[],x=>[item,...x]);await notifyAssignmentStudents(input.assignmentId,{type:'assessment',title:'Jauns summatīvais vērtējums',message:item.title,href:'/projects'});return item;}
export async function saveSummativeResult(input,user){let saved=null,eventTitle='Summative',assignmentId=null;await updateJson('summativeAssessments',[],events=>events.map(event=>{if(event.id!==input.eventId)return event;eventTitle=event.title||eventTitle;assignmentId=event.assignmentId;const scores=(event.criteria||[]).map(c=>({name:c.name,max:Number(c.max),score:Math.max(0,Math.min(Number(input.scores?.find(s=>s.name===c.name)?.score||0),Number(c.max)))}));const total=scores.reduce((s,x)=>s+x.score,0),maxTotal=scores.reduce((s,x)=>s+x.max,0),percent=maxTotal?Math.round(total/maxTotal*100):0;saved={studentId:input.studentId,scores,total,maxTotal,percent,grade:gradeFromPercent(percent),feedback:(input.feedback||'').trim(),gradedBy:user.id,publishedAt:new Date().toISOString()};return {...event,results:[saved,...(event.results||[]).filter(r=>r.studentId!==input.studentId)]};}));if(saved){saved.reward=await rewardGradedAssessment({studentId:input.studentId,sourceId:input.eventId,sourceType:'summative',grade:saved.grade,label:`${eventTitle} · grade ${saved.grade}`});const project=(await readJson('projects',[])).find(p=>p.studentId===input.studentId&&p.assignmentId===assignmentId);await notifyStudent(input.studentId,{type:'grade',title:'Summatīvais novērtēts',message:`${eventTitle} · atzīme ${saved.grade}`,href:project?`/projects/${project.id}`:'/projects',projectId:project?.id,assignmentId});}return saved;}
