'use client';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { LayoutDashboard, Users, FolderGit2, UserRound, GraduationCap, BrainCircuit, ClipboardCheck, Settings, LogOut, Search, Moon, Sun, PanelLeftClose, PanelLeftOpen, ShoppingBag } from 'lucide-react';
import { useEffect,useState } from 'react';
const teacherNav=[['/dashboard','Dashboard',LayoutDashboard],['/students','Students',Users],['/groups','Groups',GraduationCap],['/assignments','Assignments',ClipboardCheck],['/projects','Projects',FolderGit2],['/ai-reviews','AI Reviews',BrainCircuit],['/attendance','Attendance',UserRound],['/assessments','Assessments',ClipboardCheck],['/settings','Settings',Settings]];
const studentNav=[['/dashboard','Dashboard',LayoutDashboard],['/projects','My Projects',FolderGit2],['/attendance','Attendance',UserRound],['/assessments','Assessments',ClipboardCheck],['/shop','DevCredits Shop',ShoppingBag]];
export default function AppShell({user,children}){const path=usePathname(),router=useRouter();const [dark,setDark]=useState(false);const [open,setOpen]=useState(true);useEffect(()=>{const d=localStorage.getItem('theme')==='dark'||(!localStorage.getItem('theme')&&matchMedia('(prefers-color-scheme: dark)').matches);setDark(d);document.documentElement.dataset.theme=d?'dark':'light';},[]);function toggle(){const d=!dark;setDark(d);localStorage.setItem('theme',d?'dark':'light');document.documentElement.dataset.theme=d?'dark':'light';}async function logout(){await fetch('/api/auth/logout',{method:'POST'});router.push('/login');router.refresh();}const nav=user.role==='student'?studentNav:teacherNav;return <div className="app-shell"><aside className={`sidebar ${open?'':'collapsed'}`}><div className="brand"><div className="brand-mark">D</div>{open&&<div><b>DevTrack</b><small>Developer growth</small></div>}</div><nav>{nav.map(([href,label,Icon])=><Link key={href} href={href} className={path===href||path.startsWith(href+'/')?'active':''}><Icon size={18}/>{open&&<span>{label}</span>}</Link>)}</nav><div className="sidebar-foot"><button onClick={()=>setOpen(!open)}>{open?<PanelLeftClose size={18}/>:<PanelLeftOpen size={18}/>} {open&&'Collapse'}</button><button onClick={logout}><LogOut size={18}/>{open&&'Sign out'}</button></div></aside><main className="main"><header className="topbar"><button className="search-button" onClick={()=>document.dispatchEvent(new Event('devtrack-search'))}><Search size={17}/><span>Search students, projects…</span><kbd>⌘ K</kbd></button><div className="top-actions"><button className="icon-btn" onClick={toggle}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><div className="avatar">{user.firstName?.[0]}{user.lastName?.[0]}</div><div className="user-mini"><b>{user.firstName} {user.lastName}</b><span>{user.role}</span></div></div></header><div className="page">{children}</div></main><GlobalSearch teacher={user.role!=='student'}/></div>}
function GlobalSearch({teacher}){const [open,setOpen]=useState(false);const [q,setQ]=useState('');useEffect(()=>{const f=()=>setOpen(true);const key=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setOpen(true)}if(e.key==='Escape')setOpen(false)};document.addEventListener('devtrack-search',f);document.addEventListener('keydown',key);return()=>{document.removeEventListener('devtrack-search',f);document.removeEventListener('keydown',key)}},[]);if(!open)return null;const links=teacher?[['Students','/students'],['Assignments','/assignments'],['Projects','/projects'],['Groups','/groups'],['AI Reviews','/ai-reviews']]:[['My Projects','/projects'],['Assessments','/assessments'],['Attendance','/attendance'],['DevCredits Shop','/shop']];return <div className="modal-backdrop" onMouseDown={()=>setOpen(false)}><div className="command" onMouseDown={e=>e.stopPropagation()}><div className="command-input"><Search size={18}/><input autoFocus placeholder="Search…" value={q} onChange={e=>setQ(e.target.value)}/><kbd>ESC</kbd></div><div className="command-results"><p>Quick navigation</p>{links.filter(x=>x[0].toLowerCase().includes(q.toLowerCase())).map(x=><Link key={x[1]} href={x[1]} onClick={()=>setOpen(false)}>{x[0]}</Link>)}</div></div></div>}
