'use client';
import Link from 'next/link';
import { usePathname,useRouter } from 'next/navigation';
import { LayoutDashboard,Users,FolderGit2,UserRound,GraduationCap,BrainCircuit,ClipboardCheck,Settings,LogOut,Search,Moon,Sun,PanelLeftClose,PanelLeftOpen,ShoppingBag,Coins,Trophy,X,Sparkles,Gift,Music2 } from 'lucide-react';
import { useCallback,useEffect,useState } from 'react';
import { avatarAsset } from '@/lib/avatarAssets';
const teacherNav=[['/dashboard','Dashboard',LayoutDashboard],['/students','Students',Users],['/groups','Groups',GraduationCap],['/assignments','Assignments',ClipboardCheck],['/projects','Projects',FolderGit2],['/music','Classroom Music',Music2],['/ai-reviews','AI Reviews',BrainCircuit],['/attendance','Attendance',UserRound],['/assessments','Assessments',ClipboardCheck],['/settings','Settings',Settings]];
const studentNav=[['/dashboard','Dashboard',LayoutDashboard],['/projects','My Projects',FolderGit2],['/classmates','Classmates',Users],['/music','Classroom Music',Music2],['/achievements','Achievements',Trophy],['/attendance','Attendance',UserRound],['/assessments','Assessments',ClipboardCheck],['/shop','DevCredits Shop',ShoppingBag]];
export default function AppShell({user,children}){
  const path=usePathname(),router=useRouter();
  const[dark,setDark]=useState(false),[open,setOpen]=useState(true),[game,setGame]=useState(null),[catalog,setCatalog]=useState([]),[unlock,setUnlock]=useState(null),[nowPlaying,setNowPlaying]=useState(null);
  useEffect(()=>{const d=localStorage.getItem('theme')==='dark'||(!localStorage.getItem('theme')&&matchMedia('(prefers-color-scheme: dark)').matches);setDark(d);document.documentElement.dataset.theme=d?'dark':'light'},[]);
  const loadGame=useCallback(()=>{if(user.role!=='student'){delete document.documentElement.dataset.cosmeticTheme;return}let cancelled=false;fetch('/api/gamification',{cache:'no-store'}).then(r=>r.json()).then(d=>{if(cancelled||!d.ok)return;setGame(d.profile);setCatalog(d.shop||[]);const theme=(d.shop||[]).find(i=>i.id===d.profile?.equipped?.ui_theme);if(theme?.preview)document.documentElement.dataset.cosmeticTheme=theme.preview;else delete document.documentElement.dataset.cosmeticTheme;const key=`devtrack_seen_achievements_${user.id}`,current=d.profile?.achievements||[],stored=localStorage.getItem(key);if(stored===null){localStorage.setItem(key,JSON.stringify(current));return}let seen=[];try{seen=JSON.parse(stored)||[]}catch{}const fresh=current.filter(id=>!seen.includes(id));if(fresh.length){const id=fresh[fresh.length-1],a=d.achievements?.[id];setUnlock({id,...a,rewards:(a?.rewards||[]).map(rid=>(d.shop||[]).find(i=>i.id===rid)).filter(Boolean)});localStorage.setItem(key,JSON.stringify([...new Set([...seen,...current])]))}}).catch(()=>{});return()=>{cancelled=true}},[user.id,user.role]);
  useEffect(()=>{const cleanup=loadGame();const refresh=()=>loadGame();window.addEventListener('devtrack-gamification-refresh',refresh);return()=>{cleanup?.();window.removeEventListener('devtrack-gamification-refresh',refresh)}},[loadGame,path]);
  useEffect(()=>{let alive=true;async function loadNow(){try{const r=await fetch(`/api/spotify?t=${Date.now()}`,{cache:'no-store'}),d=await r.json();if(alive&&r.ok)setNowPlaying(d.connected?d.nowPlaying:null)}catch{}}loadNow();const timer=setInterval(loadNow,5000);const refresh=()=>loadNow();window.addEventListener('devtrack-data-refresh',refresh);return()=>{alive=false;clearInterval(timer);window.removeEventListener('devtrack-data-refresh',refresh)}},[]);
  function toggle(){const d=!dark;setDark(d);localStorage.setItem('theme',d?'dark':'light');document.documentElement.dataset.theme=d?'dark':'light'}
  async function logout(){delete document.documentElement.dataset.cosmeticTheme;await fetch('/api/auth/logout',{method:'POST'});router.push('/login');router.refresh()}
  const nav=user.role==='student'?studentNav:teacherNav,item=id=>catalog.find(x=>x.id===id),equippedTitle=item(game?.equipped?.title)?.value,equippedSlug=item(game?.equipped?.slug)?.value,equippedAvatarId=game?.equipped?.avatar,equippedAvatar=item(equippedAvatarId)?.value,avatarSrc=avatarAsset(equippedAvatarId),frameId=game?.equipped?.avatar_frame,avatarClass=frameId?`cosmetic-${frameId.replaceAll('_','-')}`:'';
  const progress=nowPlaying?Math.min(100,Math.round((nowPlaying.progressMs||0)/Math.max(1,nowPlaying.durationMs||1)*100)):0;
  return <div className="app-shell"><aside className={`sidebar ${open?'':'collapsed'}`}><div className="brand"><div className="brand-mark">D</div>{open&&<div><b>DevTrack</b><small>Developer growth</small></div>}</div><nav>{nav.map(([href,label,Icon])=><Link key={href} href={href} className={path===href||path.startsWith(href+'/')?'active':''}><Icon size={18}/>{open&&<span>{label}</span>}</Link>)}</nav><div className="sidebar-bottom">{nowPlaying&&<Link href="/music" className={`sidebar-now-playing ${open?'':'compact'}`}>{nowPlaying.image?<img src={nowPlaying.image} alt=""/>:<div className="sidebar-now-fallback"><Music2 size={15}/></div>}{open&&<div><span>NOW PLAYING</span><b>{nowPlaying.title}</b><small>{nowPlaying.artist}</small><div className="sidebar-now-progress"><i style={{width:`${progress}%`}}/></div></div>}</Link>}<div className="sidebar-foot"><button onClick={()=>setOpen(!open)}>{open?<PanelLeftClose size={18}/>:<PanelLeftOpen size={18}/>} {open&&'Collapse'}</button><button onClick={logout}><LogOut size={18}/>{open&&'Sign out'}</button></div></div></aside><main className="main"><header className="topbar"><div className="topbar-spacer"/><div className="top-actions">{user.role==='student'&&game&&<Link href="/shop" className="reward-chip"><Coins size={13}/>{game.credits} DC · Lv {game.level}</Link>}<button className="icon-btn" onClick={toggle}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><div className={`avatar ${avatarClass}`}>{avatarSrc?<img src={avatarSrc} alt=""/>:equippedAvatar||<>{user.firstName?.[0]}{user.lastName?.[0]}</>}</div><div className="user-mini"><b>{user.firstName} {user.lastName}</b>{equippedTitle?<span className="equipped-title">{equippedTitle}</span>:<span>{user.role}</span>}{equippedSlug&&<small className="equipped-slug">#{equippedSlug}</small>}</div></div></header><div className="page">{children}</div></main><GlobalSearch teacher={user.role!=='student'}/>{unlock&&<AchievementUnlock achievement={unlock} close={()=>setUnlock(null)}/>}</div>}
function AchievementUnlock({achievement,close}){return <div className="achievement-unlock-backdrop" onMouseDown={close}><div className={`achievement-unlock-modal rarity-${achievement.rarity||'common'}`} onMouseDown={e=>e.stopPropagation()}><button className="achievement-unlock-close" onClick={close}><X size={18}/></button><div className="achievement-unlock-icon"><Trophy size={36}/><span><Sparkles size={14}/> ACHIEVEMENT UNLOCKED</span></div><h2>{achievement.name}</h2><p>{achievement.description}</p>{achievement.rewards?.length>0&&<div className="achievement-unlock-rewards"><div><Gift size={14}/><b>New cosmetics unlocked</b></div>{achievement.rewards.map(item=><div className="unlock-reward-chip" key={item.id}>{avatarAsset(item.id)?<img src={avatarAsset(item.id)} alt=""/>:<Sparkles size={16}/>}<span>{item.name}<small>{item.type?.replace('_',' ')}</small></span></div>)}</div>}<button className="btn primary" onClick={close}>Continue</button></div></div>}
function GlobalSearch({teacher}){const[open,setOpen]=useState(false),[q,setQ]=useState('');useEffect(()=>{const key=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setOpen(true)}if(e.key==='Escape')setOpen(false)};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[]);if(!open)return null;const links=teacher?[['Students','/students'],['Assignments','/assignments'],['Projects','/projects'],['Groups','/groups'],['Classroom Music','/music'],['AI Reviews','/ai-reviews']]:[['My Projects','/projects'],['Classmates','/classmates'],['Classroom Music','/music'],['Achievements','/achievements'],['Assessments','/assessments'],['Attendance','/attendance'],['DevCredits Shop','/shop']];return <div className="modal-backdrop" onMouseDown={()=>setOpen(false)}><div className="command" onMouseDown={e=>e.stopPropagation()}><div className="command-input"><Search size={18}/><input autoFocus placeholder="Search…" value={q} onChange={e=>setQ(e.target.value)}/><kbd>ESC</kbd></div><div className="command-results"><p>Quick navigation</p>{links.filter(x=>x[0].toLowerCase().includes(q.toLowerCase())).map(x=><Link key={x[1]} href={x[1]} onClick={()=>setOpen(false)}>{x[0]}</Link>)}</div></div></div>}
