'use client';
import { useMemo,useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { Badge } from './UI';
import RichTextContent from './RichTextContent';

export default function AssignmentDetail({assignment,group,students,projects,events,commits=[],assessments=[]}){
  const router=useRouter();const [title,setTitle]=useState('Formatīvais');const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [description,setDescription]=useState('');const [criteria,setCriteria]=useState([{name:'Progress',max:5},{name:'Git workflow',max:3},{name:'Koda kvalitāte',max:2}]);const [busy,setBusy]=useState(false);const [active,setActive]=useState(events[0]?.id||'');const [drafts,setDrafts]=useState({});const [message,setMessage]=useState('');const event=events.find(e=>e.id===active);const totalMax=useMemo(()=>criteria.reduce((s,c)=>s+Number(c.max||0),0),[criteria]);const connectedCount=projects.filter(p=>p.githubRepo).length;
  async function refresh(){router.refresh();await new Promise(r=>setTimeout(r,80));router.refresh();}
  async function createEvent(){if(busy)return;try{setBusy(true);setMessage('');const r=await fetch('/api/formative',{method:'POST',headers:{'content-type':'application/json'},cache:'no-store',body:JSON.stringify({action:'create',assignmentId:assignment.id,title,date,description,criteria})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not add formative');setMessage('Formatīvais publicēts.');setDescription('');await refresh();}catch(e){setMessage(e.message)}finally{setBusy(false)}}
  function draftFor(studentId){const existing=event?.results?.find(r=>r.studentId===studentId);return drafts[studentId]||{scores:(event?.criteria||[]).map(c=>({name:c.name,score:existing?.scores?.find(s=>s.name===c.name)?.score||0})),positive:existing?.positive||'',improvement:existing?.improvement||'',feedback:existing?.feedback||''}}
  function patch(studentId,patchData){setDrafts({...drafts,[studentId]:{...draftFor(studentId),...patchData}})}
  async function save(studentId){if(busy)return;try{setBusy(true);setMessage('');const d=draftFor(studentId);const r=await fetch('/api/formative',{method:'POST',headers:{'content-type':'application/json'},cache:'no-store',body:JSON.stringify({action:'grade',eventId:event.id,studentId,...d})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Could not save result');setMessage('Vērtējums saglabāts un publicēts studentam.');setDrafts(prev=>{const n={...prev};delete n[studentId];return n});await refresh();}catch(e){setMessage(e.message)}finally{setBusy(false)}}
  return <>
    <section className="panel assignment-brief"><div className="panel-title"><div><h3>{assignment.title}</h3><small>{group?.name} · deadline {assignment.deadline}</small></div><Badge tone="purple">{students.length} students</Badge></div><RichTextContent html={assignment.descriptionHtml} fallback={assignment.description}/>{assignment.requirements?.length>0&&<><h4>Requirements</h4><ul className="brief-requirements">{assignment.requirements.map(x=><li key={x}>{x}</li>)}</ul></>}<h4>Final criteria</h4>{assignment.rubric?.map(x=><div className="setting-row" key={x.name}><span>{x.name}</span><b>{x.max} p.</b></div>)}</section>
    {message&&<div className="notice">{message}</div>}
    <section className="panel gradebook-panel"><div className="panel-title"><div><h3>Grade overview</h3><small>One place for transferring results to e-klase.</small></div><Badge tone="purple">{assessments.length}/{students.length} final grades</Badge></div><div className="table-wrap"><table className="gradebook-table"><thead><tr><th>Student</th>{events.map(e=><th key={e.id}>{e.title}<small>{e.date}</small></th>)}<th>Final points</th><th>Grade</th><th></th></tr></thead><tbody>{students.map(s=>{const project=projects.find(p=>p.studentId===s.id);const a=project?assessments.find(x=>x.projectId===project.id):null;return <tr key={s.id}><td><b>{s.firstName} {s.lastName}</b></td>{events.map(e=>{const r=(e.results||[]).find(x=>x.studentId===s.id);return <td key={e.id}>{r?<><b>{r.total}/{r.maxTotal}</b><small>{r.percent}%</small></>:<span className="muted">—</span>}</td>})}<td>{a?<b>{a.total}/{a.maxTotal}</b>:<span className="muted">—</span>}</td><td>{a?<span className="grade-pill">{a.grade}</span>:<span className="muted">—</span>}</td><td>{project&&<Link className="btn secondary compact" href={`/projects/${project.id}`}>Open</Link>}</td></tr>})}</tbody></table></div></section>
    <section className="panel"><div className="panel-title"><div><h3>Student projects</h3><small>Each student owns their GitHub connection and links their own repository.</small></div><div className="inline-row"><Badge tone="green">{connectedCount} connected</Badge><Badge tone="amber">{Math.max(students.length-connectedCount,0)} missing</Badge></div></div><div className="table-wrap"><table><thead><tr><th>Student</th><th>Repository</th><th>Commits</th><th>Last activity</th><th>Status</th><th></th></tr></thead><tbody>{students.map(s=>{const project=projects.find(p=>p.studentId===s.id);const pc=project?commits.filter(c=>c.repositoryId===project.id).sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp)):[];const last=pc[0]?.timestamp;return <tr key={s.id}><td><b>{s.firstName} {s.lastName}</b></td><td>{project?.githubRepo?<span>{project.githubOwner}/{project.githubRepo}</span>:<span className="muted">Not connected by student</span>}</td><td>{pc.length}</td><td>{last?new Date(last).toLocaleString('lv-LV'):'—'}</td><td><Badge tone={project?.githubRepo?'green':'amber'}>{project?.githubRepo?'Connected':'Waiting'}</Badge></td><td>{project?<Link className="btn secondary compact" href={`/projects/${project.id}`}>Open</Link>:<span>—</span>}</td></tr>})}</tbody></table></div></section>
    <div className="two-col"><section className="panel"><div className="panel-title"><h3>Add formative diary entry</h3><span>{totalMax} points</span></div><div className="form-row"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Formatīvais #1"/><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="What is being assessed today?"/>{criteria.map((c,i)=><div className="inline-row" key={i}><input value={c.name} onChange={e=>setCriteria(criteria.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/><input type="number" min="1" value={c.max} onChange={e=>setCriteria(criteria.map((x,j)=>j===i?{...x,max:Number(e.target.value)}:x))}/></div>)}<button className="btn secondary" disabled={busy} onClick={()=>setCriteria([...criteria,{name:'',max:1}])}>+ Criterion</button><button className="btn primary" onClick={createEvent} disabled={busy}>{busy?'Adding…':'Announce formative'}</button></div></section><section className="panel"><div className="panel-title"><h3>Project diary entries</h3><Badge>{events.length}</Badge></div>{events.map(e=><button key={e.id} className={`project-row ${active===e.id?'active':''}`} onClick={()=>setActive(e.id)}><span><b>{e.title}</b><small>{e.date} · {e.criteria.reduce((s,c)=>s+c.max,0)} p.</small></span></button>)}</section></div>
    {event&&<section className="panel"><div className="panel-title"><div><h3>{event.title}</h3><small>{event.date} · results become visible to the student immediately after Save</small></div><Badge tone="purple">Grade group</Badge></div>{students.map(s=>{const d=draftFor(s.id),project=projects.find(p=>p.studentId===s.id);return <div className="criterion formative-grade-row" key={s.id}><div className="panel-title"><div><b>{s.firstName} {s.lastName}</b><small>{project?.githubRepo?`${project.githubOwner}/${project.githubRepo}`:'Repository not connected by student'}</small></div>{project&&<Link className="btn secondary compact" href={`/projects/${project.id}`}>Open project</Link>}</div><div className="inline-row">{event.criteria.map((c,i)=><label className="formative-score" key={c.name}><span>{c.name}</span><div className="score-input"><input type="number" min="0" max={c.max} value={d.scores[i]?.score||0} onChange={e=>patch(s.id,{scores:d.scores.map((x,j)=>j===i?{...x,score:Number(e.target.value)}:x)})}/><span>/ {c.max}</span></div></label>)}</div><div className="form-grid"><input placeholder="+ Positive" value={d.positive} onChange={e=>patch(s.id,{positive:e.target.value})}/><input placeholder="Needs improvement" value={d.improvement} onChange={e=>patch(s.id,{improvement:e.target.value})}/><textarea className="span-2" placeholder="Teacher feedback" value={d.feedback} onChange={e=>patch(s.id,{feedback:e.target.value})}/></div><div className="form-actions"><button className="btn primary" disabled={busy} onClick={()=>save(s.id)}>{busy?'Saving…':'Save & publish result'}</button></div></div>})}</section>}
  </>;
}
