'use client';
import { useMemo,useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { Plus,X,Award,ClipboardCheck,GitBranch } from 'lucide-react';
import { Badge } from './UI';
import RichTextContent from './RichTextContent';

export default function AssignmentDetail({assignment,group,students,projects,events=[],summatives=[],commits=[],assessments=[]}){
 const router=useRouter(),[modal,setModal]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const connected=projects.filter(p=>p.githubRepo).length;
 async function created(){setModal(null);router.refresh();setTimeout(()=>router.refresh(),180)}
 return <div className="assignment-hub">
  <section className="panel assignment-brief compact-brief"><div className="panel-title"><div><h3>{assignment.title}</h3><small>{group?.name} · deadline {assignment.deadline}</small></div><Badge tone="purple">{students.length} students</Badge></div><RichTextContent html={assignment.descriptionHtml} fallback={assignment.description}/></section>
  {message&&<div className="notice">{message}</div>}
  <section className="panel final-grade-board"><div className="panel-title"><div><span className="eyebrow">FINAL RESULT</span><h2>Gala atzīme</h2><small>Galvenais projekta rezultāts, ko pārnest uz e-klasi.</small></div><Badge tone="purple">{assessments.length}/{students.length} graded</Badge></div><div className="table-wrap"><table className="gradebook-table"><thead><tr><th>Student</th><th>Final points</th><th>Grade</th><th></th></tr></thead><tbody>{students.map(s=>{const p=projects.find(x=>x.studentId===s.id),a=p&&assessments.find(x=>x.projectId===p.id);return <tr key={s.id}><td><b>{s.firstName} {s.lastName}</b></td><td>{a?<b>{a.total}/{a.maxTotal}</b>:'—'}</td><td>{a?<span className="grade-pill">{a.grade}</span>:'—'}</td><td>{p&&<Link className="btn secondary compact" href={`/projects/${p.id}`}>Review</Link>}</td></tr>})}</tbody></table></div></section>
  <div className="assessment-stream-grid"><AssessmentStream title="Summatīvie" subtitle="Projektā var būt vairāki summatīvie vērtējumi." icon={<Award size={17}/>} items={summatives} students={students} projects={projects} kind="summative" onAdd={()=>setModal('summative')}/><AssessmentStream title="Formatīvie" subtitle="Ātri starpvērtējumi projekta gaitā." icon={<ClipboardCheck size={17}/>} items={events} students={students} projects={projects} kind="formative" onAdd={()=>setModal('formative')}/></div>
  <section className="panel project-roster"><div className="panel-title"><div><h3>Student projects</h3><small>GitHub savienojums un pēdējā aktivitāte.</small></div><div className="inline-row"><Badge tone="green">{connected} connected</Badge><Badge tone="amber">{Math.max(students.length-connected,0)} missing</Badge></div></div><div className="table-wrap"><table><thead><tr><th>Student</th><th>Repository</th><th>Commits</th><th>Last activity</th><th></th></tr></thead><tbody>{students.map(s=>{const p=projects.find(x=>x.studentId===s.id),pc=p?commits.filter(c=>c.repositoryId===p.id).sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp)):[];return <tr key={s.id}><td><b>{s.firstName} {s.lastName}</b></td><td>{p?.githubRepo?`${p.githubOwner}/${p.githubRepo}`:<span className="muted">Not connected</span>}</td><td>{pc.length}</td><td>{pc[0]?new Date(pc[0].timestamp).toLocaleString('lv-LV'):'—'}</td><td>{p&&<Link className="btn secondary compact" href={`/projects/${p.id}`}>Open</Link>}</td></tr>})}</tbody></table></div></section>
  {modal&&<AssessmentCreateModal kind={modal} assignment={assignment} busy={busy} setBusy={setBusy} close={()=>setModal(null)} done={created} setMessage={setMessage}/>} 
 </div>
}

function AssessmentStream({title,subtitle,icon,items,students,projects,kind,onAdd}){return <section className="panel assessment-stream"><div className="panel-title"><div><h3>{icon}{title}</h3><small>{subtitle}</small></div><button className="btn primary compact" onClick={onAdd}><Plus size={14}/> Pievienot</button></div>{items.length?<div className="assessment-event-list">{items.map(e=>{const graded=e.results?.length||0;return <div className="assessment-event" key={e.id}><div><b>{e.title}</b><small>{e.date} · {e.criteria?.reduce((s,c)=>s+Number(c.max||0),0)||0} p.</small></div><div className="event-progress"><span>{graded}/{students.length} evaluated</span></div><div className="event-students">{students.map(s=>{const p=projects.find(x=>x.studentId===s.id),r=e.results?.find(x=>x.studentId===s.id);return p?<Link key={s.id} href={`/projects/${p.id}`} className={r?'done':''}>{s.firstName} {r?(kind==='summative'?`· ${r.grade}`:`· ${r.percent}%`):'· —'}</Link>:null})}</div></div>})}</div>:<div className="assessment-stream-empty">Vēl nav pievienots neviens {kind==='summative'?'summatīvais':'formatīvais'} vērtējums.</div>}</section>}

function AssessmentCreateModal({kind,assignment,busy,setBusy,close,done,setMessage}){const isSummative=kind==='summative';const [title,setTitle]=useState(isSummative?'Summatīvais #1':'Formatīvais #1'),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[description,setDescription]=useState(''),[criteria,setCriteria]=useState((assignment.rubric?.length?assignment.rubric:[{name:'Koda kvalitāte',max:5}]).map(c=>({name:c.name,max:Number(c.max)})));const total=useMemo(()=>criteria.reduce((s,c)=>s+Number(c.max||0),0),[criteria]);async function submit(){if(busy)return;setBusy(true);try{const r=await fetch(isSummative?'/api/summative':'/api/formative',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'create',assignmentId:assignment.id,title,date,description,criteria})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not create assessment');setMessage(`${isSummative?'Summatīvais':'Formatīvais'} pievienots.`);done()}catch(e){setMessage(e.message)}finally{setBusy(false)}}return <div className="assessment-popup-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="assessment-popup"><header><div><span className="eyebrow">NEW ASSESSMENT</span><h2>{isSummative?'Pievienot summatīvo':'Pievienot formatīvo'}</h2></div><button className="icon-btn" onClick={close}><X size={17}/></button></header><div className="assessment-popup-body"><label><span>Nosaukums</span><input value={title} onChange={e=>setTitle(e.target.value)}/></label><label><span>Datums</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label><span>Apraksts</span><textarea rows="3" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Ko šajā vērtējumā pārbauda?"/></label><div className="popup-criteria-head"><b>Kritēriji</b><span>{total} punkti</span></div>{criteria.map((c,i)=><div className="popup-criterion" key={i}><input value={c.name} onChange={e=>setCriteria(criteria.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/><input type="number" min="1" value={c.max} onChange={e=>setCriteria(criteria.map((x,j)=>j===i?{...x,max:Number(e.target.value)}:x))}/><button onClick={()=>setCriteria(criteria.filter((_,j)=>j!==i))}>×</button></div>)}<button className="btn secondary compact" onClick={()=>setCriteria([...criteria,{name:'',max:1}])}><Plus size={13}/> Criterion</button></div><footer><button className="btn secondary" onClick={close}>Cancel</button><button className="btn primary" disabled={busy||!title.trim()||!criteria.length} onClick={submit}>{busy?'Saving…':'Create assessment'}</button></footer></div></div>}
