'use client';

import { useCallback,useEffect,useMemo,useRef,useState } from 'react';
import { Ban,CheckCircle2,CircleDollarSign,Clock3,Headphones,History,Music2,PauseCircle,Pencil,Search,ShieldAlert,Trash2,UserX,X } from 'lucide-react';

const emptyBan={studentId:'',durationMinutes:60,reason:'',severity:'medium',fine:500};

export default function ClassroomMusic({user}){
  const [data,setData]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState('');
  const [query,setQuery]=useState(''),[results,setResults]=useState([]),[searching,setSearching]=useState(false),[nowPlaying,setNowPlaying]=useState(null),[banForm,setBanForm]=useState(emptyBan);
  const [clock,setClock]=useState(()=>Date.now());
  const searchTimer=useRef(null),isStudent=user.role==='student';

  const loadMusic=useCallback(async()=>{try{const r=await fetch(`/api/music?t=${Date.now()}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load music');setData(prev=>mergeRemote(prev,d));setError('')}catch(e){setError(e.message)}finally{setLoading(false)}},[]);
  const loadSpotify=useCallback(async()=>{try{const r=await fetch(`/api/spotify?t=${Date.now()}`,{cache:'no-store'}),d=await r.json();if(r.ok)setNowPlaying(d.connected?d.nowPlaying:null)}catch{}},[]);

  useEffect(()=>{const start=setTimeout(()=>{loadMusic();loadSpotify()},0),musicTimer=setInterval(loadMusic,4000),spotifyTimer=setInterval(loadSpotify,6000),clockTimer=setInterval(()=>setClock(Date.now()),30000),focus=()=>{setClock(Date.now());loadMusic();loadSpotify()};window.addEventListener('focus',focus);return()=>{clearTimeout(start);clearInterval(musicTimer);clearInterval(spotifyTimer);clearInterval(clockTimer);window.removeEventListener('focus',focus)}},[loadMusic,loadSpotify]);

  async function mutate(payload,{key=payload.action,optimistic,rollback}={}){
    if(busy)return null;setBusy(key);setError('');if(optimistic)setData(prev=>optimistic(prev));
    try{
      const r=await fetch('/api/music',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload),cache:'no-store'}),d=await r.json();
      if(!r.ok)throw new Error(d.error||'Action failed');const result=d.result;
      if(payload.action==='request'&&result)setData(prev=>replaceOptimistic(prev,payload._tempId,result));
      if(payload.action==='toggle_requests'&&result)setData(prev=>prev?{...prev,settings:{...prev.settings,...result}}:prev);
      if(payload.action==='pay_fine'&&result)setData(prev=>prev?{...prev,access:result}:prev);
      if(['ban_student','unban_student'].includes(payload.action)&&result)setData(prev=>prev?{...prev,students:(prev.students||[]).map(s=>s.id===result.studentId?{...s,access:result}:s)}:prev);
      window.dispatchEvent(new Event('devtrack-data-refresh'));return result||true;
    }catch(e){if(rollback)setData(prev=>rollback(prev));setError(e.message);return null}finally{setBusy('')}
  }

  async function addTrack(track){const tempId=`temp_${Date.now()}_${track.id}`,temp={id:tempId,studentId:user.id,studentName:`${user.firstName} ${user.lastName}`,title:track.title,artist:track.artist,spotifyUrl:track.spotifyUrl,spotifyId:track.id,spotifyUri:track.uri,image:track.image,durationMs:track.durationMs,explicit:track.explicit,status:'requested',createdAt:new Date().toISOString(),_optimistic:true};setQuery('');setResults([]);return mutate({action:'request',title:track.title,artist:track.artist,spotifyUrl:track.spotifyUrl,spotifyId:track.id,spotifyUri:track.uri,image:track.image,durationMs:track.durationMs,explicit:track.explicit,_tempId:tempId},{key:track.id,optimistic:prev=>prev?{...prev,queue:[...(prev.queue||[]),temp]}:prev,rollback:prev=>prev?{...prev,queue:(prev.queue||[]).filter(x=>x.id!==tempId)}:prev})}
  async function removeTrack(item,admin=false){const payload=admin?{action:'moderate_request',requestId:item.id,status:'removed'}:{action:'remove_request',requestId:item.id};return mutate(payload,{key:`remove_${item.id}`,optimistic:prev=>prev?{...prev,queue:(prev.queue||[]).filter(x=>x.id!==item.id),history:admin?[{...item,status:'removed',removedAt:new Date().toISOString()},...(prev.history||[])]:prev.history}:prev,rollback:prev=>prev?{...prev,queue:[...(prev.queue||[]),item].sort(sortCreated),history:(prev.history||[]).filter(x=>x.id!==item.id)}:prev})}
  async function searchSpotify(term=query){const q=term.trim();if(q.length<2){setResults([]);return}setSearching(true);try{const r=await fetch(`/api/spotify?q=${encodeURIComponent(q)}&t=${Date.now()}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Spotify search failed');setResults(d.results||[])}catch(e){setError(e.message)}finally{setSearching(false)}}
  function changeQuery(value){setQuery(value);clearTimeout(searchTimer.current);if(value.trim().length<2){setResults([]);return}searchTimer.current=setTimeout(()=>searchSpotify(value),300)}
  function editBan(student){const access=student.access||{},remaining=Math.max(1,Math.ceil((new Date(access.banUntil||Date.now()).getTime()-Date.now())/60000));setBanForm({studentId:student.id,durationMinutes:remaining,reason:access.banReason||'',severity:access.severity||'medium',fine:Number(access.fineDue||0)})}
  async function saveBan(){const done=await mutate({action:'ban_student',...banForm},{key:'ban'});if(done)setBanForm(emptyBan)}

  const activeBan=useMemo(()=>Boolean(data?.access?.banUntil&&new Date(data.access.banUntil).getTime()>clock),[data,clock]),rulesNeeded=isStudent&&data&&data.access?.acceptedRulesVersion!==data.rulesVersion;
  if(loading&&!data)return <div className="music-loading"><Music2 size={24}/><span>Loading Classroom Music…</span></div>;
  if(!data)return <div className="notice danger">{error||'Classroom Music unavailable.'}</div>;
  return <div className="music-page"><section className="music-hero"><div><span className="eyebrow">CLASSROOM MUSIC</span><h1>One classroom. One queue.</h1><p>Requests, history and access controls in one live view.</p></div><div className={`music-status ${data.settings.requestsEnabled?'open':'paused'}`}><Headphones size={18}/><div><b>{data.settings.requestsEnabled?'Requests open':'Requests paused'}</b><span>{data.settings.spotifyConnected?'Spotify connected':'Spotify not connected'}</span></div></div></section>{error&&<div className="notice danger music-error">{error}</div>}{isStudent?<StudentView data={data} user={user} query={query} changeQuery={changeQuery} setQuery={setQuery} results={results} setResults={setResults} searching={searching} activeBan={activeBan} busy={busy} addTrack={addTrack} removeTrack={removeTrack} mutate={mutate}/>:<AdminView data={data} nowPlaying={nowPlaying} banForm={banForm} setBanForm={setBanForm} editBan={editBan} saveBan={saveBan} busy={busy} removeTrack={removeTrack} mutate={mutate} clock={clock}/>} {rulesNeeded&&<RulesModal rules={data.rules} busy={busy} accept={()=>mutate({action:'accept_rules'},{key:'accept_rules',optimistic:prev=>prev?{...prev,access:{...prev.access,acceptedRulesVersion:prev.rulesVersion}}:prev})}/>}</div>;
}

function StudentView({data,user,query,changeQuery,setQuery,results,setResults,searching,activeBan,busy,addTrack,removeTrack,mutate}){const blocked=activeBan||Number(data.access?.fineDue||0)>0||!data.settings.requestsEnabled;return <><Penalty data={data} activeBan={activeBan} busy={busy} mutate={mutate}/><div className="music-layout"><main><section className="panel music-request-panel"><div className="panel-title"><div><h3><Music2 size={17}/> Add music</h3><small>Search once, tap once — it is added immediately.</small></div></div>{data.settings.spotifyConnected?<div className="spotify-search-wrap"><div className="spotify-search"><Search size={17}/><input value={query} onChange={e=>changeQuery(e.target.value)} placeholder="Search song, artist or album…" disabled={blocked}/>{query&&<button className="spotify-clear" type="button" onClick={()=>{setQuery('');setResults([])}}><X size={14}/></button>}<span>{searching?'Searching…':'Spotify'}</span></div>{results.length>0&&<div className="spotify-results">{results.map(t=><button key={t.id} className="spotify-result" disabled={blocked||busy===t.id} onClick={()=>addTrack(t)}>{t.image?<img src={t.image} alt=""/>:<div className="spotify-cover"><Music2 size={17}/></div>}<span><b>{t.title}</b><small>{t.artist}{t.explicit?' · E':''}</small></span><strong>{busy===t.id?'Adding…':'+ Add'}</strong></button>)}</div>}</div>:<div className="music-empty-state"><Music2/><b>Spotify is not connected yet.</b><span>Ask the teacher to connect Spotify.</span></div>}</section><Queue queue={data.queue} userId={user.id} removeTrack={removeTrack}/></main><aside><RulesMini rules={data.rules}/></aside></div></>}

function AdminView({data,nowPlaying,banForm,setBanForm,editBan,saveBan,busy,removeTrack,mutate,clock}){return <div className="music-admin-layout music-admin-v2"><main><section className="panel music-admin-controls"><div className="panel-title"><div><h3><Headphones size={17}/> Classroom controls</h3><small>Changes apply immediately.</small></div><div className="music-admin-actions">{!data.spotifyConnected&&<a className="btn primary compact" href="/api/spotify/connect">Connect Spotify</a>}<button className="btn secondary compact" onClick={()=>mutate({action:'toggle_requests',enabled:!data.settings.requestsEnabled},{key:'toggle',optimistic:prev=>prev?{...prev,settings:{...prev.settings,requestsEnabled:!prev.settings.requestsEnabled}}:prev})}>{data.settings.requestsEnabled?<><PauseCircle size={14}/> Pause requests</>:<>Open requests</>}</button></div></div></section><Queue queue={data.queue} nowPlaying={nowPlaying} admin removeTrack={removeTrack}/><MusicHistory items={data.history||[]}/></main><aside><section className="panel"><div className="panel-title"><div><h3><Ban size={17}/> {banForm.studentId?'Edit restriction':'Restrict music access'}</h3><small>Ban + optional DevCredits fine</small></div></div><div className="music-ban-form"><label><span>Student</span><select value={banForm.studentId} onChange={e=>setBanForm({...banForm,studentId:e.target.value})}><option value="">Choose student…</option>{data.students.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><div className="music-ban-row"><label><span>Duration</span><select value={banForm.durationMinutes} onChange={e=>setBanForm({...banForm,durationMinutes:Number(e.target.value)})}><option value={30}>30 min</option><option value={60}>1 hour</option><option value={240}>4 hours</option><option value={1440}>1 day</option><option value={10080}>7 days</option><option value={43200}>30 days</option></select></label><label><span>Severity</span><select value={banForm.severity} onChange={e=>setBanForm({...banForm,severity:e.target.value})}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label></div><label><span>Reason</span><textarea value={banForm.reason} onChange={e=>setBanForm({...banForm,reason:e.target.value})}/></label><label><span>Fine (DC)</span><input type="number" min="0" value={banForm.fine} onChange={e=>setBanForm({...banForm,fine:Number(e.target.value)})}/></label><div className="music-ban-actions">{banForm.studentId&&<button className="btn secondary" onClick={()=>setBanForm(emptyBan)}>Cancel</button>}<button className="btn danger" disabled={!banForm.studentId||!banForm.reason||busy==='ban'} onClick={saveBan}><Ban size={15}/> {busy==='ban'?'Saving…':'Save restriction'}</button></div></div></section><BanList students={data.students||[]} editBan={editBan} busy={busy} unban={student=>mutate({action:'unban_student',studentId:student.id},{key:`unban_${student.id}`})} clock={clock}/></aside></div>}

function Queue({queue=[],nowPlaying,admin=false,userId,removeTrack}){const initialWait=nowPlaying?.isPlaying?Math.max(0,Number(nowPlaying.durationMs||0)-Number(nowPlaying.progressMs||0)):0,{rows,totalWait}=queue.reduce((acc,q)=>({rows:[...acc.rows,{...q,eta:acc.totalWait}],totalWait:acc.totalWait+Math.max(0,Number(q.durationMs||0))}),{rows:[],totalWait:initialWait});return <section className="panel music-queue-panel"><div className="panel-title"><div><h3><Clock3 size={17}/> Classroom queue</h3><small>{rows.length?`${rows.length} song${rows.length===1?'':'s'} · about ${formatWait(totalWait)} queued`:'No songs queued'}</small></div></div>{rows.length?<div className="music-queue-list">{rows.map((q,i)=><div className={`music-queue-row ${q._optimistic?'pending':''}`} key={q.id}>{q.image?<img className="music-queue-cover" src={q.image} alt=""/>:<div className="music-queue-cover music-thumb-fallback"><Music2 size={16}/></div>}<div className="music-position">{i+1}</div><div className="music-song"><b>{q.title}</b><span>{q.artist}</span><small>{q.studentName} · {formatDuration(q.durationMs)} · {q.eta<30000?'next up':`~${formatWait(q.eta)} wait`}</small></div><span className={`music-state ${q.status}`}>{q._optimistic?'Adding…':statusText(q.status)}</span>{(admin||q.studentId===userId)&&!q._optimistic&&<div className="music-admin-actions"><button title="Remove" onClick={()=>removeTrack(q,admin)}><Trash2 size={14}/></button></div>}</div>)}</div>:<div className="music-empty-state"><Music2 size={26}/><b>The queue is empty.</b><span>Someone has to choose the first song.</span></div>}</section>}

function MusicHistory({items}){return <section className="panel music-history"><div className="panel-title"><div><h3><History size={17}/> Request history</h3><small>Played, removed and failed requests remain visible.</small></div><span className="music-history-count">{items.length}</span></div>{items.length?<div className="music-history-list">{items.map(item=><div className="music-history-row" key={item.id}>{item.image?<img src={item.image} alt=""/>:<div className="music-history-cover"><Music2 size={15}/></div>}<div><b>{item.title}</b><span>{item.artist}</span><small>{item.studentName} · {new Date(item.playedAt||item.removedAt||item.updatedAt||item.createdAt).toLocaleString('lv-LV')}</small></div><span className={`music-state ${item.status}`}>{statusText(item.status)}</span></div>)}</div>:<div className="music-empty-state"><History size={25}/><b>No history yet.</b><span>Completed requests will appear here.</span></div>}</section>}
function BanList({students,editBan,unban,busy,clock}){const restricted=students.filter(s=>s.access&&(Number(s.access.fineDue||0)>0||new Date(s.access.banUntil||0).getTime()>clock));return <section className="panel music-ban-list"><div className="panel-title"><div><h3><UserX size={17}/> Ban list</h3><small>Active restrictions and unpaid fines.</small></div><span className="music-history-count">{restricted.length}</span></div>{restricted.length?<div className="music-ban-list-rows">{restricted.map(student=><div className="music-ban-item" key={student.id}><div><b>{student.name}</b><span>{student.access.banReason||'Music access restricted'}</span><small>{new Date(student.access.banUntil||0).getTime()>clock?`Until ${new Date(student.access.banUntil).toLocaleString('lv-LV')}`:'Ban expired'}{student.access.fineDue?` · ${student.access.fineDue} DC due`:''}</small></div><div><button title="Edit" onClick={()=>editBan(student)}><Pencil size={14}/></button><button title="Remove restriction" disabled={busy===`unban_${student.id}`} onClick={()=>unban(student)}><CheckCircle2 size={14}/></button></div></div>)}</div>:<div className="music-empty-state compact"><CheckCircle2 size={22}/><b>No active bans.</b></div>}</section>}

function mergeRemote(prev,remote){if(!prev)return remote;const pending=(prev.queue||[]).filter(x=>x._optimistic),remoteIds=new Set((remote.queue||[]).map(x=>x.spotifyId||x.id)),still=pending.filter(x=>!remoteIds.has(x.spotifyId||x.id)&&Date.now()-new Date(x.createdAt).getTime()<15000);return {...remote,queue:[...(remote.queue||[]),...still].sort(sortCreated)}}
function replaceOptimistic(prev,tempId,result){if(!prev)return prev;return {...prev,queue:[...(prev.queue||[]).filter(x=>x.id!==tempId&&x.id!==result.id),result].sort(sortCreated)}}
function sortCreated(a,b){return new Date(a.createdAt)-new Date(b.createdAt)}
function Penalty({data,activeBan,busy,mutate}){if(!activeBan&&!data.access?.fineDue)return null;return <section className="music-penalty-card"><Ban/><div><h2>{activeBan?'Temporary ban active':'Fine payment required'}</h2>{activeBan&&<p>Until {new Date(data.access.banUntil).toLocaleString('lv-LV')}. {data.access.banReason}</p>}{data.access?.fineDue>0&&<p><b>{data.access.fineDue} DC</b> must be paid before requesting again.</p>}</div>{data.access?.fineDue>0&&<button className="btn primary" disabled={busy==='pay_fine'} onClick={()=>mutate({action:'pay_fine'},{key:'pay_fine'})}><CircleDollarSign size={16}/> Pay {data.access.fineDue} DC</button>}</section>}
function RulesMini({rules}){return <section className="panel music-rules-mini"><div className="panel-title"><h3><ShieldAlert size={17}/> Queue rules</h3></div>{rules.map((r,i)=><div className="music-rule-mini" key={r}><span>{i+1}</span><p>{r}</p></div>)}</section>}
function RulesModal({rules,busy,accept}){return <div className="music-rules-backdrop"><div className="music-rules-modal"><ShieldAlert size={28}/><span className="eyebrow">BEFORE YOU ENTER</span><h2>Classroom Music rules</h2><p>Misuse can result in a temporary ban and a DevCredits fine.</p><div className="music-rules-list">{rules.map((r,i)=><div key={r}><span>{i+1}</span><p>{r}</p></div>)}</div><div className="music-warning"><CircleDollarSign size={16}/><span>Typical penalty: temporary ban + <b>500 DC</b>.</span></div><button className="btn primary" disabled={busy==='accept_rules'} onClick={accept}>{busy==='accept_rules'?'Saving…':'I understand and agree'}</button></div></div>}
function statusText(status){return({requested:'Adding…',queued:'Queued',played:'Played',removed:'Removed',failed:'Failed'})[status]||status}
function formatDuration(ms){const total=Math.max(0,Math.round(Number(ms||0)/1000)),m=Math.floor(total/60),s=String(total%60).padStart(2,'0');return `${m}:${s}`}
function formatWait(ms){const minutes=Math.max(0,Math.ceil(Number(ms||0)/60000));if(minutes<1)return '<1 min';if(minutes<60)return `${minutes} min`;const h=Math.floor(minutes/60),m=minutes%60;return m?`${h}h ${m}m`:`${h}h`}
