'use client';
import Link from 'next/link';
import { useEffect,useMemo,useRef,useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowLeft,Armchair,Check,Copy,DoorOpen,Grid2X2,Info,LoaderCircle,Maximize2,Move,Plus,Printer,QrCode,RotateCcw,Save,Settings2,Trash2,X,ZoomIn,ZoomOut } from 'lucide-react';
import { CLASSROOM_LIMITS,clampDeskToCanvas,findOpenDeskPosition,nextDeskCode,snapToGrid } from '@/lib/classroomLayout';

async function request(body){
  const response=await fetch('/api/classrooms',{method:'POST',headers:{'content-type':'application/json'},cache:'no-store',body:JSON.stringify(body)}),data=await response.json();
  if(!response.ok){const error=new Error(data.error||'Could not save the classroom.');error.status=response.status;error.details=data.details;throw error}
  return data;
}

export default function ClassroomEditor({initialClassroom,staffOptions,canAssign}){
  const router=useRouter(),viewportRef=useRef(null),dragRef=useRef(null),savedRef=useRef(initialClassroom),[room,setRoom]=useState(initialClassroom),[desks,setDesks]=useState(initialClassroom.desks),[selectedId,setSelectedId]=useState(null),[draggingId,setDraggingId]=useState(null),[zoom,setZoom]=useState(.8),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[conflict,setConflict]=useState(false),[settings,setSettings]=useState(false);
  const selected=desks.find(desk=>desk.id===selectedId)||null,canManage=room.canManage,canvas={width:room.canvasWidth,height:room.canvasHeight};
  const savedAt=useMemo(()=>new Intl.DateTimeFormat('en',{hour:'2-digit',minute:'2-digit'}).format(new Date(room.updatedAt)),[room.updatedAt]);

  useEffect(()=>{
    const fit=()=>{if(!viewportRef.current)return;const available=Math.max(300,viewportRef.current.clientWidth-48);setZoom(Math.max(.35,Math.min(1,available/room.canvasWidth)))};
    fit();const observer=new ResizeObserver(fit);observer.observe(viewportRef.current);return()=>observer.disconnect();
  },[room.canvasWidth]);
  useEffect(()=>{const before=event=>{if(dirty){event.preventDefault();event.returnValue=''}};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before)},[dirty]);
  useEffect(()=>{
    const key=event=>{
      if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='s'){event.preventDefault();if(canManage&&dirty&&!saving)saveLayout();return}
      if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;
      if(event.key==='Escape'){setSelectedId(null);return}
      if(!selected||!canManage||saving)return;
      if(event.key==='Delete'||event.key==='Backspace'){event.preventDefault();removeDesk(selected.id);return}
      const step=event.shiftKey?CLASSROOM_LIMITS.grid:2,movement={ArrowLeft:[-step,0],ArrowRight:[step,0],ArrowUp:[0,-step],ArrowDown:[0,step]}[event.key];
      if(movement){event.preventDefault();updateDesk(selected.id,desk=>clampDeskToCanvas({...desk,x:desk.x+movement[0],y:desk.y+movement[1]},canvas))}
    };
    window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);
  });

  function updateDesk(id,change){if(!canManage||saving)return;setDesks(items=>items.map(item=>item.id===id?(typeof change==='function'?change(item):{...item,...change}):item));setDirty(true);setNotice('');setError('')}
  function addDesk(source=null){
    if(!canManage||saving||desks.length>=CLASSROOM_LIMITS.maxDesks)return;
    const code=nextDeskCode(desks),width=source?.width||120,height=source?.height||80,position=source?{x:Math.min(source.x+40,room.canvasWidth-width),y:Math.min(source.y+40,room.canvasHeight-height)}:findOpenDeskPosition(desks,canvas,{width,height});
    const desk={id:`temp_${crypto.randomUUID()}`,code,label:source?`${source.label||source.code} copy`:code,x:snapToGrid(position.x),y:snapToGrid(position.y),width,height,qrToken:null};
    setDesks(items=>[...items,desk]);setSelectedId(desk.id);setDirty(true);setNotice('');setError('');
  }
  function removeDesk(id){if(!canManage||saving)return;setDesks(items=>items.filter(item=>item.id!==id));setSelectedId(current=>current===id?null:current);setDirty(true);setNotice('');setError('')}
  function rotateDesk(id){updateDesk(id,desk=>clampDeskToCanvas({...desk,width:desk.height,height:desk.width},canvas))}
  function changeCanvas(patch){
    if(!canManage||saving)return;const next={width:patch.width??room.canvasWidth,height:patch.height??room.canvasHeight};
    if(next.width<400||next.width>3000||next.height<300||next.height>2000)return;
    setRoom(value=>({...value,canvasWidth:next.width,canvasHeight:next.height}));setDesks(items=>items.map(desk=>clampDeskToCanvas(desk,next)));setDirty(true);setNotice('');setError('');
  }
  function resetLayout(){if(!dirty||!confirm('Discard every unsaved layout change?'))return;const saved=savedRef.current;setRoom(saved);setDesks(saved.desks);setSelectedId(null);setDirty(false);setError('');setConflict(false);setNotice('Unsaved changes discarded.')}
  async function saveLayout(){
    if(!canManage||!dirty||saving)return;setSaving(true);setError('');setConflict(false);setNotice('');
    try{const data=await request({action:'saveLayout',classroomId:room.id,version:room.version,canvasWidth:room.canvasWidth,canvasHeight:room.canvasHeight,desks:desks.map(({id,code,label,x,y,width,height})=>({id,code,label,x,y,width,height}))});savedRef.current=data.classroom;setRoom(data.classroom);setDesks(data.classroom.desks);setSelectedId(current=>data.classroom.desks.some(desk=>desk.id===current)?current:null);setDirty(false);setNotice('Layout saved. Every QR code is up to date.')}catch(cause){setError(cause.message);setConflict(cause.status===409)}finally{setSaving(false)}
  }
  async function reloadLatest(){
    if(dirty&&!confirm('Replace your unsaved layout with the latest server version?'))return;setSaving(true);setError('');
    try{const response=await fetch(`/api/classrooms?id=${room.id}`,{cache:'no-store'}),data=await response.json();if(!response.ok)throw new Error(data.error||'Could not reload classroom.');savedRef.current=data.classroom;setRoom(data.classroom);setDesks(data.classroom.desks);setSelectedId(null);setDirty(false);setConflict(false);setNotice('Latest layout loaded.')}catch(cause){setError(cause.message)}finally{setSaving(false)}
  }
  function leave(){if(!dirty||confirm('Leave without saving your layout changes?'))router.push('/classrooms')}
  function startDrag(event,desk){
    if(!canManage||saving||event.button>0)return;event.preventDefault();event.stopPropagation();setSelectedId(desk.id);setDraggingId(desk.id);dragRef.current={id:desk.id,startX:event.clientX,startY:event.clientY,x:desk.x,y:desk.y,moved:false};
    const move=moveEvent=>{const drag=dragRef.current;if(!drag)return;const dx=(moveEvent.clientX-drag.startX)/zoom,dy=(moveEvent.clientY-drag.startY)/zoom;if(Math.abs(dx)+Math.abs(dy)>2)drag.moved=true;const next=clampDeskToCanvas({...desk,x:snapToGrid(drag.x+dx),y:snapToGrid(drag.y+dy)},canvas);setDesks(items=>items.map(item=>item.id===drag.id?{...item,x:next.x,y:next.y}:item))};
    const up=()=>{const moved=dragRef.current?.moved;dragRef.current=null;setDraggingId(null);window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);window.removeEventListener('pointercancel',up);if(moved){setDirty(true);setNotice('');setError('')}};
    window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);window.addEventListener('pointercancel',up);
  }

  return <div className="classroom-editor-page">
    <header className="classroom-editor-header"><div className="classroom-editor-heading"><button className="classroom-back" onClick={leave}><ArrowLeft size={17}/></button><div><span className="eyebrow">Classroom layout</span><h1>{room.name}</h1><p>{room.slug} · version {room.version}</p></div></div><div className="classroom-save-state">{saving?<><LoaderCircle className="spin" size={15}/>Saving one transaction…</>:dirty?<><i className="dirty"/>Unsaved changes</>:<><Check size={15}/>Saved at {savedAt}</>}</div><div className="classroom-editor-head-actions">{canManage&&<button className="btn secondary" onClick={()=>setSettings(true)}><Settings2 size={15}/> Room settings</button>}{canManage&&room.desks.length>0&&<Link className="btn secondary" href={`/classrooms/${room.id}/qr`}><Printer size={15}/> Print QR</Link>}{canManage&&<button className="btn primary" disabled={!dirty||saving} onClick={saveLayout}><Save size={15}/>{saving?'Saving…':'Save layout'}{dirty&&!saving&&<kbd>⌘S</kbd>}</button>}</div></header>
    {(error||notice)&&<div className={`classroom-editor-notice ${error?'danger':'success'}`}><span>{error||notice}</span>{conflict&&<button onClick={reloadLatest}>Reload latest</button>}<button className="close" onClick={()=>{setError('');setNotice('');setConflict(false)}}><X size={14}/></button></div>}
    <div className="classroom-editor-toolbar"><div className="classroom-tool-group"><button disabled={!canManage||saving||desks.length>=CLASSROOM_LIMITS.maxDesks} onClick={()=>addDesk()}><Plus size={15}/> Add desk</button><button disabled={!canManage||!selected||saving} onClick={()=>selected&&addDesk(selected)}><Copy size={15}/> Duplicate</button><button disabled={!canManage||!selected||saving} onClick={()=>selected&&rotateDesk(selected.id)}><RotateCcw size={15}/> Rotate</button><button className="danger" disabled={!canManage||!selected||saving} onClick={()=>selected&&removeDesk(selected.id)}><Trash2 size={15}/> Delete</button></div><div className="classroom-toolbar-hint"><Move size={14}/>Drag desks · arrows nudge · Shift + arrows snap</div><div className="classroom-zoom"><button onClick={()=>setZoom(value=>Math.max(.3,value-.1))}><ZoomOut size={15}/></button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(value=>Math.min(1.5,value+.1))}><ZoomIn size={15}/></button><button onClick={()=>{const available=Math.max(300,(viewportRef.current?.clientWidth||room.canvasWidth)-48);setZoom(Math.max(.35,Math.min(1,available/room.canvasWidth)))}}><Maximize2 size={14}/></button></div></div>
    <div className="classroom-editor-workspace"><section className="classroom-canvas-viewport" ref={viewportRef} onPointerDown={event=>event.target===event.currentTarget&&setSelectedId(null)}><div className="classroom-canvas-stage" style={{width:room.canvasWidth*zoom,height:room.canvasHeight*zoom}}><div className="classroom-canvas" style={{width:room.canvasWidth,height:room.canvasHeight,transform:`scale(${zoom})`}} onPointerDown={event=>event.target===event.currentTarget&&setSelectedId(null)}><div className="classroom-front"><span>TEACHER / BOARD</span></div>{desks.map(desk=><Desk key={desk.id} desk={desk} selected={desk.id===selectedId} dragging={desk.id===draggingId} editable={canManage&&!saving} onPointerDown={event=>startDrag(event,desk)} onSelect={()=>setSelectedId(desk.id)}/>) }{!desks.length&&<div className="classroom-canvas-empty"><span><Armchair size={25}/></span><b>This room has no desks yet</b><p>Add the first desk, then drag it into place.</p>{canManage&&<button onClick={()=>addDesk()}><Plus size={14}/> Add desk</button>}</div>}</div></div></section><aside className="classroom-inspector">{selected?<DeskInspector desk={selected} canManage={canManage&&!saving} update={patch=>updateDesk(selected.id,desk=>clampDeskToCanvas({...desk,...patch},canvas))} rotate={()=>rotateDesk(selected.id)} remove={()=>removeDesk(selected.id)}/>:<RoomInspector room={room} deskCount={desks.length} canManage={canManage&&!saving} changeCanvas={changeCanvas}/>}<div className="classroom-inspector-footer"><div><Grid2X2 size={14}/><span><b>{CLASSROOM_LIMITS.grid}px grid</b><small>Positions snap automatically</small></span></div>{dirty&&canManage&&<button onClick={resetLayout}><RotateCcw size={13}/>Discard changes</button>}</div></aside></div>
    {settings&&<ClassroomSettingsModal room={room} staffOptions={staffOptions} canAssign={canAssign} dirty={dirty} onClose={()=>setSettings(false)} onSaved={updated=>{savedRef.current=updated;setRoom(current=>dirty?{...updated,canvasWidth:current.canvasWidth,canvasHeight:current.canvasHeight}:updated);if(!dirty)setDesks(updated.desks);setSettings(false);setNotice('Classroom details saved.')}}/>}
  </div>;
}

function Desk({desk,selected,dragging,editable,onPointerDown,onSelect}){return <button className={`layout-desk ${selected?'selected':''} ${dragging?'dragging':''}`} style={{left:desk.x,top:desk.y,width:desk.width,height:desk.height}} onPointerDown={onPointerDown} onClick={onSelect} title={`${desk.label||desk.code} · ${desk.code}`}><span className="layout-desk-code">{desk.code}</span><b>{desk.label||desk.code}</b><small>{desk.width} × {desk.height}</small>{desk.qrToken?<QrCode size={13}/>:<i className="layout-desk-new">NEW</i>}{editable&&<span className="layout-desk-grip"><i/><i/><i/><i/><i/><i/></span>}</button>}

function DeskInspector({desk,canManage,update,rotate,remove}){return <div className="classroom-inspector-body"><div className="classroom-inspector-title"><span><Armchair size={18}/></span><div><span className="eyebrow">Selected desk</span><h2>{desk.label||desk.code}</h2></div></div><label className="classroom-field"><span>Display label</span><input disabled={!canManage} value={desk.label} maxLength={80} onChange={event=>update({label:event.target.value})} placeholder={desk.code}/><small>The stable desk code remains {desk.code}.</small></label><div className="classroom-inspector-grid"><NumberField label="Width" value={desk.width} min={60} max={360} disabled={!canManage} onChange={width=>update({width})}/><NumberField label="Height" value={desk.height} min={40} max={260} disabled={!canManage} onChange={height=>update({height})}/><NumberField label="X position" value={desk.x} min={0} max={3000} disabled={!canManage} onChange={x=>update({x})}/><NumberField label="Y position" value={desk.y} min={0} max={2000} disabled={!canManage} onChange={y=>update({y})}/></div><div className="classroom-desk-actions"><button disabled={!canManage} onClick={rotate}><RotateCcw size={14}/>Rotate desk</button><button className="danger" disabled={!canManage} onClick={remove}><Trash2 size={14}/>Remove</button></div><div className={`classroom-qr-state ${desk.qrToken?'ready':'pending'}`}><span><QrCode size={17}/></span><div><b>{desk.qrToken?'Permanent QR ready':'QR created on save'}</b><small>{desk.qrToken?'This code stays the same when the desk moves or is renamed.':'Save the layout once to create this desk’s private token.'}</small></div></div></div>}

function RoomInspector({room,deskCount,canManage,changeCanvas}){return <div className="classroom-inspector-body"><div className="classroom-inspector-title"><span><DoorOpen size={18}/></span><div><span className="eyebrow">Room canvas</span><h2>{room.name}</h2></div></div><div className="classroom-room-summary"><div><Armchair size={16}/><span><b>{deskCount}</b><small>desks</small></span></div><div><QrCode size={16}/><span><b>{room.desks.length}</b><small>saved QR codes</small></span></div></div><div className="classroom-inspector-grid"><NumberField label="Canvas width" value={room.canvasWidth} min={400} max={3000} disabled={!canManage} onChange={width=>changeCanvas({width})}/><NumberField label="Canvas height" value={room.canvasHeight} min={300} max={2000} disabled={!canManage} onChange={height=>changeCanvas({height})}/></div><div className="classroom-editor-tips"><div><Move size={15}/><span><b>Place desks visually</b><small>Drag anywhere; the editor snaps to a clean grid.</small></span></div><div><QrCode size={15}/><span><b>Print once</b><small>QR tokens survive desk movement and label changes.</small></span></div><div><Info size={15}/><span><b>Attendance comes next</b><small>Lesson sessions will use this exact plan in phase 2.</small></span></div></div></div>}
function NumberField({label,value,min,max,disabled,onChange}){return <label className="classroom-field"><span>{label}</span><input type="number" value={value} min={min} max={max} disabled={disabled} onChange={event=>{const next=Number(event.target.value);if(Number.isFinite(next))onChange(Math.max(min,Math.min(max,Math.round(next))))}}/></label>}

export function ClassroomSettingsModal({room,staffOptions,canAssign,dirty,onClose,onSaved}){
  const [form,setForm]=useState({name:room.name,staffMembershipIds:room.staff.map(person=>person.membershipId)}),[saving,setSaving]=useState(false),[error,setError]=useState('');
  function toggle(id){setForm(value=>({...value,staffMembershipIds:value.staffMembershipIds.includes(id)?value.staffMembershipIds.filter(item=>item!==id):[...value.staffMembershipIds,id]}))}
  async function save(event){event.preventDefault();if(saving||form.name.trim().length<2)return;setSaving(true);setError('');try{const payload={action:'updateDetails',classroomId:room.id,name:form.name.trim()};if(canAssign)payload.staffMembershipIds=form.staffMembershipIds;const data=await request(payload);onSaved(data.classroom)}catch(cause){setError(cause.message);setSaving(false)}}
  return <div className="modal-backdrop classroom-modal-backdrop" onMouseDown={onClose}><form className="classroom-modal compact" onSubmit={save} onMouseDown={event=>event.stopPropagation()}><header><div><span className="eyebrow">Room settings</span><h2>Classroom details</h2><p>Rename the room and control which teachers can open it.</p></div><button type="button" className="icon-btn" onClick={onClose}><X size={18}/></button></header><div className="classroom-modal-body">{dirty&&<div className="classroom-settings-warning"><Info size={15}/>Your unsaved desk layout stays in the editor and can be saved afterwards.</div>}{error&&<div className="classroom-form-error">{error}</div>}<label className="classroom-field"><span>Classroom name</span><input autoFocus value={form.name} onChange={event=>setForm(value=>({...value,name:event.target.value}))} maxLength={120}/></label>{canAssign&&<div className="classroom-field"><span>Teachers with access</span><div className="classroom-teacher-picker">{staffOptions.map(person=><button type="button" key={person.membershipId} className={form.staffMembershipIds.includes(person.membershipId)?'selected':''} onClick={()=>toggle(person.membershipId)}><span>{person.firstName?.[0]}{person.lastName?.[0]}</span><div><b>{person.firstName} {person.lastName}</b><small>{person.email}</small></div><i>{form.staffMembershipIds.includes(person.membershipId)&&<Check size={12}/>}</i></button>)}</div><small>School admins always have access.</small></div>}</div><footer><button type="button" className="btn secondary" onClick={onClose}>Cancel</button><button className="btn primary" disabled={saving||form.name.trim().length<2}>{saving?'Saving…':'Save details'}</button></footer></form></div>;
}
