'use client';
import { useMemo,useState } from 'react';
import { useRouter } from 'next/navigation';
import { Coins,Sparkles,ShoppingBag,ShieldCheck,Trophy,Palette,Tag,Frame,Check,History,Lock,Flame,Gift,Hash } from 'lucide-react';

const typeLabel={avatar_frame:'Avatar frame',title:'Profile title',slug:'Profile slug',ui_theme:'UI theme'};
const typeIcon={avatar_frame:Frame,title:Tag,slug:Hash,ui_theme:Palette};
const filters=[['all','All'],['avatar_frame','Frames'],['title','Titles'],['slug','Slugs'],['ui_theme','Themes']];

export default function GamificationShop({user,initialProfile,initialTransactions,shop,achievements={},levelRewards=[]}){
  const router=useRouter();const [profile,setProfile]=useState(initialProfile);const [transactions,setTransactions]=useState(initialTransactions);const [busy,setBusy]=useState('');const [message,setMessage]=useState('');const [filter,setFilter]=useState('all');
  const owned=new Set(profile.inventory||[]);const nextLevelXp=Math.pow(profile.level,2)*180;const currentLevelStart=Math.pow(Math.max(0,profile.level-1),2)*180;const levelPct=Math.max(0,Math.min(100,Math.round((profile.xp-currentLevelStart)/Math.max(1,nextLevelXp-currentLevelStart)*100)));const equippedIds=new Set(Object.values(profile.equipped||{}).filter(Boolean));const inventory=useMemo(()=>shop.filter(i=>owned.has(i.id)),[shop,profile.inventory]);const visible=filter==='all'?shop:shop.filter(i=>i.type===filter);
  async function act(action,item){if(busy)return;setBusy(item.id);setMessage('');try{const r=await fetch('/api/gamification',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,itemId:item.id})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Action failed');setProfile(d.profile);setMessage(action==='buy'?`${item.name} added to your inventory.`:`${item.name} equipped.`);if(action==='buy')setTransactions([{id:`local_${Date.now()}`,type:'purchase',credits:-item.price,label:`Purchased ${item.name}`,createdAt:new Date().toISOString()},...transactions]);router.refresh()}catch(e){setMessage(e.message)}finally{setBusy('')}}
  return <div className="game-page"><section className="game-hero game-hero-wow"><div><span className="eyebrow">DEVTRACK REWARDS</span><h1>Build your developer identity.</h1><p>Grades earn XP and DevCredits. Level up, unlock cosmetics and flex your profile around the class.</p><div className="hero-meme-row"><span>YOLO</span><span>sigma 67</span><span>+1000 aura</span><span>locked in</span><span>ship it</span></div></div><div className="wallet-card"><div className="wallet-balance"><Coins size={21}/><span>DevCredits</span><strong>{profile.credits}</strong></div><div className="level-row"><div><span>Level {profile.level}</span><b>{profile.xp} XP</b></div><div className="game-progress"><span style={{width:`${levelPct}%`}}/></div><small>{Math.max(0,nextLevelXp-profile.xp)} XP to next level</small></div><a href="#level-rewards" className="next-reward"><Gift size={14}/> Next level gives {levelRewards.find(x=>x.level===profile.level+1)?.credits||'more'} DC</a></div></section>{message&&<div className="notice game-notice">{message}</div>}

  <section className="level-rewards-strip" id="level-rewards"><div className="level-rewards-head"><div><span className="eyebrow">LEVEL UP</span><h2>Level rewards</h2></div><p>Every new level permanently grants more DevCredits. Higher levels = bigger drops.</p></div><div className="level-reward-track">{levelRewards.map(r=><div key={r.level} className={`level-reward-node ${profile.level>=r.level?'claimed':r.level===profile.level+1?'next':''}`}><span>Lv {r.level}</span><b><Coins size={13}/>{r.credits}</b><small>{profile.level>=r.level?'Claimed':r.level===profile.level+1?'Next':'Locked'}</small></div>)}</div></section>

  <div className="shop-filter-bar">{filters.map(([id,label])=><button key={id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{label}<span>{id==='all'?shop.length:shop.filter(i=>i.type===id).length}</span></button>)}</div>

  <div className="game-layout"><main><div className="game-section-head"><div><h2><ShoppingBag size={20}/> Shop</h2><p>{visible.length} cosmetics in this category.</p></div></div><div className="shop-grid">{visible.map(item=>{const Icon=typeIcon[item.type]||Sparkles;const isOwned=owned.has(item.id);const equipped=equippedIds.has(item.id);const locked=profile.level<Number(item.minLevel||1);return <article className={`shop-card rarity-${item.rarity} ${locked?'shop-locked':''}`} key={item.id}><div className={`shop-preview ${item.preview||''}`}><Icon size={32}/><span>{item.rarity}</span>{item.type==='slug'&&<div className="slug-preview">#{item.value}</div>}{locked&&<div className="level-lock"><Lock size={13}/> Lv {item.minLevel}</div>}</div><div className="shop-copy"><div className="shop-type">{typeLabel[item.type]}</div><h3>{item.name}</h3><p>{item.description}</p><div className="shop-card-foot"><span className="shop-price"><Coins size={14}/>{item.price}</span>{isOwned?<button className={equipped?'btn secondary compact equipped':'btn secondary compact'} disabled={equipped||busy===item.id} onClick={()=>act('equip',item)}>{equipped?<><Check size={14}/> Equipped</>:busy===item.id?'Working…':'Equip'}</button>:<button className="btn primary compact" disabled={locked||profile.credits<item.price||busy===item.id} onClick={()=>act('buy',item)}>{locked?`Lv ${item.minLevel}`:busy===item.id?'Buying…':'Buy'}</button>}</div></div></article>})}</div></main>

  <aside className="game-sidebar"><section className="panel profile-loadout"><div className="panel-title"><div><h3><Flame size={17}/> Current loadout</h3><small>Your public class profile</small></div></div><div className="loadout-preview"><div className={`loadout-avatar ${profile.equipped?.avatar_frame||''}`}>{user.firstName?.[0]}{user.lastName?.[0]}</div><div><b>{user.firstName} {user.lastName}</b><span>{shop.find(i=>i.id===profile.equipped?.title)?.value||'Student'}</span>{profile.equipped?.slug&&<small>#{shop.find(i=>i.id===profile.equipped.slug)?.value}</small>}</div></div></section><section className="panel"><div className="panel-title"><div><h3><Trophy size={17}/> Achievements</h3><small>{(profile.achievements||[]).length} unlocked</small></div></div>{(profile.achievements||[]).length?(profile.achievements||[]).map(id=>{const a=achievements[id];return <div className="inventory-row" key={id}><span>{a?.name||id}<small>{a?.description||'Achievement unlocked'}</small></span><b>Unlocked</b></div>}):<div className="empty-state">Your achievements will appear here.</div>}</section><section className="panel inventory-panel"><div className="panel-title"><div><h3><ShieldCheck size={17}/> Inventory</h3><small>{inventory.length} items owned</small></div></div>{inventory.length?inventory.map(item=><div className="inventory-row" key={item.id}><span>{item.name}<small>{typeLabel[item.type]}</small></span>{equippedIds.has(item.id)?<b>Equipped</b>:<button className="btn secondary compact" onClick={()=>act('equip',item)}>Equip</button>}</div>):<div className="empty-state">Your first cosmetic will appear here.</div>}</section><section className="panel transaction-panel"><div className="panel-title"><div><h3><History size={17}/> Recent rewards</h3><small>Transparent credit history</small></div></div>{transactions.slice(0,10).map(t=><div className="transaction-row" key={t.id}><div><b>{t.label}</b><small>{new Date(t.createdAt).toLocaleDateString('lv-LV')}</small></div><span className={Number(t.credits)>=0?'positive':'negative'}>{Number(t.credits)>0?'+':''}{t.credits} DC</span></div>)}{!transactions.length&&<div className="empty-state">Rewards from graded projects will appear here.</div>}</section></aside></div></div>
}
