'use client';
import { useEffect,useRef,useState } from 'react';
import { useRouter,useSearchParams } from 'next/navigation';
import { Github,Link2,Loader2,RefreshCw,Settings,CheckCircle2,AlertTriangle,ExternalLink } from 'lucide-react';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
export default function GitHubConnect({project}){
  const router=useRouter(),search=useSearchParams();const [repos,setRepos]=useState([]),[busy,setBusy]=useState(false),[selected,setSelected]=useState(''),[phase,setPhase]=useState(''),[message,setMessage]=useState(''),[menu,setMenu]=useState(false);const running=useRef(false);
  async function status(){const r=await fetch(`/api/github/status?projectId=${encodeURIComponent(project.id)}&t=${Date.now()}`,{cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not read GitHub status');return d}
  async function load(){if(!project.githubInstallationId)return;setBusy(true);try{const r=await fetch(`/api/github/repos?installationId=${project.githubInstallationId}`,{cache:'no-store'});const d=await r.json();setRepos(d.repos||[])}finally{setBusy(false)}}
  async function waitForLinked(maxMs=30000){const started=Date.now();while(Date.now()-started<maxMs){try{const s=await status();if(s.linked)return s}catch{}await sleep(1000)}return null}
  async function finishConnected(s){setPhase('done');setMessage(`${s?.owner||project.githubOwner}/${s?.repo||project.githubRepo} ir pieslēgts.`);router.replace(`/projects/${project.id}`);router.refresh();await sleep(650);setPhase('')}
  async function syncInBackground(){fetch('/api/github/sync',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectId:project.id})}).then(()=>router.refresh()).catch(()=>{})}
  async function connectFlow(){if(running.current)return;running.current=true;setPhase('connecting');setMessage('Pārbaudām GitHub savienojumu…');try{const linked=await waitForLinked(45000);if(!linked)throw new Error('Repository link was not confirmed in time');await finishConnected(linked);syncInBackground()}catch(e){const current=await status().catch(()=>null);if(current?.linked){await finishConnected(current);syncInBackground()}else{setPhase('error');setMessage(e.message||'Neizdevās pieslēgt GitHub.')}}finally{running.current=false}}
  useEffect(()=>{if(project.githubInstallationId&&!project.githubRepo){const timer=setTimeout(load,0);return()=>clearTimeout(timer)}},[project.githubInstallationId,project.githubRepo]);
  useEffect(()=>{if(search.get('github')==='syncing'&&!phase){const timer=setTimeout(connectFlow,0);return()=>clearTimeout(timer)}},[search]);
  async function link(){if(!selected)return;setBusy(true);setPhase('connecting');setMessage('Piesaistām izvēlēto repozitoriju…');try{const r=await fetch('/api/github/link',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectId:project.id,repoId:Number(selected)})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not link repository');const linked=await waitForLinked(20000);if(!linked)throw new Error('Repository link was not confirmed');await finishConnected(linked);syncInBackground()}catch(e){setPhase('error');setMessage(e.message||'Neizdevās pieslēgt GitHub.')}finally{setBusy(false)}}
  async function manualSync(){setMenu(false);setPhase('connecting');setMessage('Atjaunojam GitHub datus…');try{await fetch('/api/github/sync',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectId:project.id})});setPhase('done');setMessage('GitHub dati atjaunoti.');router.refresh();await sleep(650);setPhase('')}catch{setPhase('error');setMessage('Neizdevās atjaunot GitHub datus.')}}
  return <>
    {project.githubRepo?<div className="github-compact"><div className="github-status"><CheckCircle2 size={16}/><span><b>GitHub connected</b><small>{project.githubOwner}/{project.githubRepo}</small></span></div><div className="github-settings-wrap"><button className="icon-btn" onClick={()=>setMenu(!menu)} title="GitHub settings"><Settings size={17}/></button>{menu&&<div className="github-menu"><a href={`https://github.com/${project.githubOwner}/${project.githubRepo}`} target="_blank" rel="noreferrer"><ExternalLink size={15}/> Open repository</a><button onClick={manualSync}><RefreshCw size={15}/> Sync now</button><a href={`https://github.com/settings/installations/${project.githubInstallationId}`} target="_blank" rel="noreferrer"><Settings size={15}/> Manage access</a></div>}</div></div>:
    !project.githubInstallationId?<a className="btn secondary" href={`/api/github/install?projectId=${project.id}`}><Github size={16}/> Connect GitHub</a>:
    <div className="repo-connect"><select value={selected} onChange={e=>setSelected(e.target.value)} disabled={busy}><option value="">Select repository…</option>{repos.map(r=><option key={r.id} value={r.id}>{r.fullName}{r.private?' · private':''}</option>)}</select><button className="btn primary" onClick={link} disabled={!selected||busy}>{busy?<Loader2 size={16} className="spin"/>:<Link2 size={16}/>} Link repository</button></div>}
    {phase&&<div className="github-loader-backdrop"><div className="github-loader-card">{phase==='done'?<CheckCircle2 size={38} className="github-loader-success"/>:phase==='error'?<AlertTriangle size={38}/>:<Loader2 size={38} className="spin"/>}<div><h3>{phase==='error'?'GitHub connection failed':phase==='done'?'GitHub connected':'Connecting GitHub…'}</h3><p>{message}</p>{phase==='error'&&<button className="btn secondary" onClick={()=>setPhase('')}>Close</button>}</div></div></div>}
  </>;
}
