'use client';
import { useMemo,useState } from 'react';
import { useRouter } from 'next/navigation';
import { Badge } from './UI';
import { Plus,Upload,Trash2,KeyRound,Pencil,UserMinus,UsersRound } from 'lucide-react';

const api='/api/groups/manage';
async function act(body){const r=await fetch(api,{method:'POST',headers:{'content-type':'application/json'},cache:'no-store',body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Operation failed');return d;}
function parseCsv(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];const sep=lines[0].includes(';')?';':',';const head=lines[0].split(sep).map(x=>x.trim().toLowerCase());const idx=(...names)=>head.findIndex(h=>names.includes(h));const fi=idx('firstname','first_name','vards','vārds'),li=idx('lastname','last_name','uzvards','uzvārds'),ei=idx('email','e-mail','epasts','e-pasts');if(fi<0||li<0||ei<0)throw new Error('CSV vajag kolonnas: firstName,lastName,email');return lines.slice(1).map(line=>{const c=line.split(sep).map(x=>x.trim().replace(/^"|"$/g,''));return{firstName:c[fi]||'',lastName:c[li]||'',email:c[ei]||''}}).filter(x=>x.firstName&&x.lastName&&x.email)}

export default function GroupManager({initialGroups,users,defaultPassword}){
  const router=useRouter();
  const [selected,setSelected]=useState(initialGroups[0]?.id||'');const [name,setName]=useState('');const [student,setStudent]=useState({firstName:'',lastName:'',email:''});const [editing,setEditing]=useState(null);const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);
  const group=initialGroups.find(g=>g.id===selected)||initialGroups[0];
  const members=useMemo(()=>group?(group.studentIds||[]).map(id=>users.find(u=>u.id===id)).filter(Boolean):[],[group,users]);
  async function refresh(){router.refresh();await new Promise(r=>setTimeout(r,80));router.refresh();}
  async function run(body,success){if(busy)return;try{setBusy(true);setMsg('');const d=await act(body);setMsg(success+(d.defaultPassword?` Default password: ${d.defaultPassword}`:''));if(body.action==='addStudent')setStudent({firstName:'',lastName:'',email:''});if(body.action==='createGroup')setName('');if(body.action==='updateStudent')setEditing(null);await refresh();}catch(e){setMsg(e.message)}finally{setBusy(false)}}
  async function importFile(file){if(busy)return;try{setBusy(true);const students=parseCsv(await file.text());if(!students.length)throw new Error('CSV nav studentu');const d=await act({action:'importStudents',groupId:selected,students});setMsg(`Importēti ${d.created}. Izlaisti ${d.skipped.length}. Default password: ${d.defaultPassword}`);await refresh();}catch(e){setMsg(e.message)}finally{setBusy(false)}}
  return <div className="management-layout">
    <aside className="management-sidebar"><section className="panel"><div className="panel-title"><div><h3>Groups</h3><small>Create and switch cohorts</small></div><Badge>{initialGroups.length}</Badge></div><div className="field"><label>New group</label><div className="form-actions"><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. IPa24"/><button className="btn primary" disabled={busy||!name.trim()} onClick={()=>run({action:'createGroup',name},'Group created.')}><Plus size={16}/> Add</button></div></div><div className="management-list">{initialGroups.map(g=><button key={g.id} className={group?.id===g.id?'active':''} onClick={()=>setSelected(g.id)}><span><b>{g.name}</b><small>{g.studentIds?.length||0} students</small></span><Badge>{g.studentIds?.length||0}</Badge></button>)}</div></section></aside>
    <div className="management-content">{group?<><section className="section-card"><div className="section-card-header"><div><h3>{group.name}</h3><p>{members.length} students · Default first-login password: <b>{defaultPassword}</b></p></div><button className="btn secondary compact" disabled={busy} onClick={()=>{const n=prompt('New group name',group.name);if(n)run({action:'renameGroup',groupId:group.id,name:n},'Group renamed.')}}><Pencil size={14}/> Rename group</button></div>{msg&&<div className="notice">{msg}</div>}<div className="form-grid three" style={{marginTop:msg?14:0}}><div className="field"><label>First name</label><input placeholder="Jānis" value={student.firstName} onChange={e=>setStudent({...student,firstName:e.target.value})}/></div><div className="field"><label>Last name</label><input placeholder="Bērziņš" value={student.lastName} onChange={e=>setStudent({...student,lastName:e.target.value})}/></div><div className="field"><label>Email</label><input type="email" placeholder="student@school.lv" value={student.email} onChange={e=>setStudent({...student,email:e.target.value})}/></div></div><div className="toolbar" style={{marginTop:12}}><div className="form-actions"><button className="btn primary" disabled={busy||!student.firstName||!student.lastName||!student.email} onClick={()=>run({action:'addStudent',groupId:group.id,student},'Student created.')}><Plus size={16}/> {busy?'Saving…':'Add student'}</button><label className={`btn secondary csv-upload ${busy?'disabled':''}`}><Upload size={16}/> Import CSV<input disabled={busy} type="file" accept=".csv,text/csv" onChange={e=>e.target.files?.[0]&&importFile(e.target.files[0])}/></label></div><div className="form-help csv-help">CSV headers: <b>firstName,lastName,email</b>. Comma and semicolon separators are supported.</div></div></section>
    <section className="section-card"><div className="section-card-header"><div><h3>Students</h3><p>Manage accounts, passwords and group membership.</p></div><Badge>{members.length}</Badge></div>{members.length===0?<div className="empty-state"><UsersRound size={24}/><p>No students in this group yet.</p></div>:<div className="student-list">{members.map(s=><div className="student-row" key={s.id}><div className="student-main"><span className="student-avatar">{s.firstName?.[0]}{s.lastName?.[0]}</span><div><b>{s.firstName} {s.lastName}</b><small>{s.email}</small></div></div><div className="student-status"><span className={`status-dot ${s.mustChangePassword?'warning':''}`}/><span>{s.mustChangePassword?'Password change required':'Active account'}</span></div><div className="row-actions"><button className="btn secondary compact" disabled={busy} onClick={()=>setEditing(editing===s.id?null:s.id)}><Pencil size={14}/> Edit</button><button className="btn secondary compact" disabled={busy} onClick={()=>run({action:'resetPassword',studentId:s.id},'Password reset.')}><KeyRound size={14}/> Reset</button><button className="btn secondary compact" disabled={busy} onClick={()=>confirm('Remove student from this group?')&&run({action:'removeFromGroup',groupId:group.id,studentId:s.id},'Student removed from group.')}><UserMinus size={14}/> Remove</button><button className="btn danger compact" disabled={busy} onClick={()=>confirm(`Delete ${s.firstName} ${s.lastName} account completely? This also deletes their project data.`)&&run({action:'deleteStudent',studentId:s.id},'Student deleted.')}><Trash2 size={14}/> Delete</button></div>{editing===s.id&&<div className="edit-row"><EditStudent student={s} onSave={data=>run({action:'updateStudent',studentId:s.id,student:data},'Student updated.')} busy={busy}/></div>}</div>)}</div>}</section></>:<section className="section-card empty-state">Select a group to manage students.</section>}</div>
  </div>;
}
function EditStudent({student,onSave,busy}){const [v,setV]=useState({firstName:student.firstName,lastName:student.lastName,email:student.email});return <div className="form-grid"><div className="field"><label>First name</label><input value={v.firstName} onChange={e=>setV({...v,firstName:e.target.value})}/></div><div className="field"><label>Last name</label><input value={v.lastName} onChange={e=>setV({...v,lastName:e.target.value})}/></div><div className="field span-2"><label>Email</label><input type="email" value={v.email} onChange={e=>setV({...v,email:e.target.value})}/></div><div className="form-actions span-2"><button className="btn primary" disabled={busy} onClick={()=>onSave(v)}>{busy?'Saving…':'Save changes'}</button></div></div>}
