'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Highlight,themes } from 'prism-react-renderer';
import { Folder,FolderOpen,FileCode2,GitCommitHorizontal,RefreshCw,Sparkles,Check,AlertTriangle,Plus,Minus,CalendarDays,BookOpen,Github,ChevronRight,Home,Clock3,Target,MessageSquareText,Award,Code2,BarChart3,History,UserCheck,UserX,Clock } from 'lucide-react';
import { Badge,Progress } from './UI';
import { Bars,Heatmap } from './Charts';
import GitHubConnect from './GitHubConnect';
import RichTextContent from './RichTextContent';
import CriteriaModal from './CriteriaModal';

export default function ProjectWorkspace({project,assignment,formative,student,commits,feedback,assessment,review,tree,defaultFile,githubError,series,heatmap,attendance=[],user}){
  const isStudent=user.role==='student';
  const [tab,setTab]=useState('Overview');
  const [devTab,setDevTab]=useState('Code');
  const [criteriaOpen,setCriteriaOpen]=useState(false);
  const [file,setFile]=useState(defaultFile);
  const [content,setContent]=useState(defaultFile?.content||'');
  const [busy,setBusy]=useState(false);
  const [nodes,setNodes]=useState(tree||[]);
  const [folder,setFolder]=useState('');
  const tabs=isStudent?['Overview','Diary','Development','Assessment']:['Overview','Diary','Development','Assessment','Teacher tools'];

  async function openFile(path){setBusy(true);try{const r=await fetch(`/api/github/file?projectId=${project.id}&path=${encodeURIComponent(path)}`,{cache:'no-store'});const d=await r.json();if(d.ok){setFile({path});setContent(d.file.content)}else alert(d.error||'Could not load file')}finally{setBusy(false)}}
  async function openFolder(path){setBusy(true);try{const r=await fetch(`/api/github/tree?projectId=${project.id}&path=${encodeURIComponent(path)}`,{cache:'no-store'});const d=await r.json();if(d.ok){setNodes(d.tree||[]);setFolder(path);setFile(null);setContent('')}else alert(d.error||'Could not open folder')}finally{setBusy(false)}}
  async function runReview(){setBusy(true);const r=await fetch('/api/ai/review',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectId:project.id})});setBusy(false);if(r.ok)location.reload();else alert((await r.json()).error)}
  async function sync(){setBusy(true);const r=await fetch('/api/github/sync',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectId:project.id})});setBusy(false);if(r.ok)location.reload();else alert((await r.json()).error||'GitHub sync failed')}
  const present=attendance.filter(a=>['present','late','attended','here'].includes(String(a.status||'').toLowerCase())).length;
  const attendancePct=attendance.length?Math.round(present/attendance.length*100):null;

  return <>
    {!isStudent&&assignment&&<div className="workspace-back"><Link className="btn secondary" href={`/assignments/${assignment.id}`}>← Back to {assignment.title} students</Link></div>}
    <div className="project-head simplified-head"><div><span className="repo-owner">{isStudent?'Project workspace':`${student.firstName} ${student.lastName}`}</span><h1>{project.name}</h1><div className="inline-row"><Badge tone="purple">{project.status}</Badge>{project.deadline&&<Badge>Due {project.deadline}</Badge>}</div></div><div className="header-actions"><button className="btn secondary" onClick={()=>setCriteriaOpen(true)}><Target size={16}/> Criteria</button>{isStudent?<GitHubConnect project={project}/>:project.githubRepo?<a className="btn secondary" href={`https://github.com/${project.githubOwner}/${project.githubRepo}`} target="_blank" rel="noreferrer"><Github size={16}/> {project.githubOwner}/{project.githubRepo}</a>:<Badge tone="amber">Repository not connected</Badge>}</div></div>

    <div className="tabs workspace-tabs simplified-tabs">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={tab===t?'active':''}>{t}</button>)}</div>

    {tab==='Overview'&&<Overview assignment={assignment} project={project} commits={commits} attendance={attendance} attendancePct={attendancePct} formative={formative} feedback={feedback} assessment={assessment} openCriteria={()=>setCriteriaOpen(true)}/>} 
    {tab==='Diary'&&<Diary formative={formative} feedback={feedback} attendance={attendance} studentId={student.id}/>} 
    {tab==='Development'&&<Development devTab={devTab} setDevTab={setDevTab} nodes={nodes} folder={folder} file={file} content={content} busy={busy} project={project} student={student} githubError={githubError} isStudent={isStudent} openFolder={openFolder} openFile={openFile} commits={commits} series={series} heatmap={heatmap} sync={sync}/>} 
    {tab==='Assessment'&&<Assessment a={assessment} user={user} project={project} assignment={assignment} openCriteria={()=>setCriteriaOpen(true)}/>} 
    {tab==='Teacher tools'&&!isStudent&&<TeacherTools review={review} runReview={runReview} busy={busy} feedback={feedback} user={user} project={project}/>} 
    <CriteriaModal open={criteriaOpen} onClose={()=>setCriteriaOpen(false)} rubric={assignment?.rubric||[]}/>
  </>;
}

function Overview({assignment,project,commits,attendance,attendancePct,formative,feedback,assessment,openCriteria}){
  const latest=[];(formative||[]).forEach(e=>latest.push({date:e.date,title:e.title,type:'Assessment'}));(feedback||[]).forEach(f=>latest.push({date:f.createdAt,title:f.text,type:'Feedback'}));latest.sort((a,b)=>new Date(b.date)-new Date(a.date));
  return <div className="overview-stack"><section className="overview-summary calm-summary"><div className="summary-card"><span>Deadline</span><b>{assignment?.deadline||project.deadline||'—'}</b><small><Clock3 size={13}/> Project schedule</small></div><div className="summary-card"><span>Repository</span><b>{project.githubRepo?'Connected':'Not connected'}</b><small><Github size={13}/> {project.githubRepo?`${project.githubOwner}/${project.githubRepo}`:'Connect GitHub to start'}</small></div><div className="summary-card"><span>Attendance</span><b>{attendancePct===null?'—':`${attendancePct}%`}</b><small><CalendarDays size={13}/> {attendance.length?`${attendance.length} lessons recorded`:'DeskPlan data will appear here'}</small></div><div className="summary-card"><span>Current grade</span><b>{assessment?.grade??'—'}</b><small><Award size={13}/> {assessment?`${assessment.total}/${assessment.maxTotal} points`:'Not graded yet'}</small></div></section><div className="overview-main calm-overview"><section className="panel assignment-document"><div className="panel-title"><div><h3><BookOpen size={18}/> Project brief</h3><small>Everything you need to know about the task.</small></div></div><RichTextContent html={assignment?.descriptionHtml} fallback={assignment?.description||project.assignment||'No assignment description.'}/>{assignment?.requirements?.length>0&&<><h4>Requirements</h4><ul className="brief-requirements">{assignment.requirements.map(x=><li key={x}>{x}</li>)}</ul></>}</section><aside className="overview-side"><section className="panel compact-panel"><div className="panel-title"><div><h3><Target size={17}/> Assessment</h3><small>{assignment?.rubric?.length||0} criteria</small></div></div><p className="muted-copy">View exactly what will be assessed and how many points each criterion is worth.</p><button className="btn secondary wide" onClick={openCriteria}>View criteria</button></section><section className="panel compact-panel"><div className="panel-title"><div><h3><History size={17}/> Latest activity</h3></div></div>{latest.slice(0,3).map((x,i)=><div className="latest-row" key={i}><span>{x.type}</span><b>{x.title}</b><small>{new Date(x.date).toLocaleDateString('lv-LV')}</small></div>)}{!latest.length&&<p className="empty">No activity yet.</p>}</section></aside></div></div>
}

function Development({devTab,setDevTab,nodes,folder,file,content,busy,project,student,githubError,isStudent,openFolder,openFile,commits,series,heatmap,sync}){
  return <div className="development-page"><div className="development-toolbar"><div className="segmented-control"><button className={devTab==='Code'?'active':''} onClick={()=>setDevTab('Code')}><Code2 size={15}/> Code</button><button className={devTab==='Commits'?'active':''} onClick={()=>setDevTab('Commits')}><History size={15}/> Commits</button><button className={devTab==='Activity'?'active':''} onClick={()=>setDevTab('Activity')}><BarChart3 size={15}/> Activity</button></div><button className="btn secondary compact" onClick={sync} disabled={busy||!project.githubRepo}><RefreshCw size={14}/> Sync</button></div>{devTab==='Code'&&<CodeBrowser nodes={nodes} folder={folder} file={file} content={content} busy={busy} project={project} student={student} githubError={githubError} isStudent={isStudent} openFolder={openFolder} openFile={openFile}/>} {devTab==='Commits'&&<section className="panel"><div className="panel-title"><h3>Commit history</h3><Badge>{commits.length}</Badge></div><div className="commit-list">{commits.map(c=><div className="commit" key={c.sha}><GitCommitHorizontal size={18}/><div><b>{c.message.split('\n')[0]}</b><span>{c.author} · {new Date(c.timestamp).toLocaleString('lv-LV')}</span></div><code>{c.sha.slice(0,7)}</code><div className="diffstat"><span className="add">+{c.additions}</span><span className="del">-{c.deletions}</span></div></div>)}</div></section>} {devTab==='Activity'&&<div className="two-col"><section className="panel"><div className="panel-title"><h3>Commits per week</h3></div><Bars data={series}/></section><section className="panel"><div className="panel-title"><h3>Contribution activity</h3></div><Heatmap days={heatmap}/><div className="risk-box">{commits.length<3?<><AlertTriangle size={18}/> Development activity is still low.</>:<><Check size={18}/> Development activity is visible.</>}</div></section></div>}</div>
}

function CodeBrowser({nodes,folder,file,content,busy,project,githubError,isStudent,openFolder,openFile}){const crumbs=folder?folder.split('/'):[];return <div className="repo-grid"><div className="filetree"><div className="tree-breadcrumb"><button onClick={()=>openFolder('')}><Home size={14}/></button>{crumbs.map((part,i)=>{const p=crumbs.slice(0,i+1).join('/');return <span key={p}><ChevronRight size={12}/><button onClick={()=>openFolder(p)}>{part}</button></span>})}</div>{folder&&<button className="tree-up" onClick={()=>openFolder(crumbs.slice(0,-1).join('/'))}>← ..</button>}{nodes.length===0?<div className="tree-empty"><Github size={20}/><p>{project.githubRepo?'This folder is empty.':isStudent?'Connect a repository to browse code.':'Repository is not connected.'}</p></div>:nodes.map(n=><button key={n.path} onClick={()=>n.type==='tree'?openFolder(n.path):openFile(n.path)} className={file?.path===n.path?'active':''}>{n.type==='tree'?<Folder size={15}/>:<FileCode2 size={15}/>}<span>{n.path.split('/').pop()}</span>{n.type==='tree'&&<ChevronRight size={13} className="tree-chevron"/>}</button>)}</div><div className="code-panel"><div className="code-meta"><span>{file?.path||folder||'Repository root'}</span><span>{busy?'Loading…':project.defaultBranch||'main'}</span></div>{githubError&&!file&&!project.githubRepo&&<div className="code-empty"><p className="review-issue"><AlertTriangle size={18}/><span>{githubError}</span></p></div>}{!file&&project.githubRepo&&<div className="code-welcome"><FolderOpen size={36}/><h3>Browse repository</h3><p>Open a folder or select a file.</p></div>}{file&&<Highlight theme={themes.nightOwl} code={content} language={language(file.path)}>{({className,style,tokens,getLineProps,getTokenProps})=><pre className={className} style={{...style,margin:0,background:'transparent'}}>{tokens.map((line,i)=><div key={i} {...getLineProps({line})}><span className="line-no">{i+1}</span>{line.map((token,key)=><span key={key} {...getTokenProps({token})}/>)}</div>)}</pre>}</Highlight>}</div></div>}

function Diary({formative,feedback,attendance,studentId}){
  const entries=[];
  (formative||[]).forEach(e=>{const result=(e.results||[]).find(r=>r.studentId===studentId);entries.push({date:e.date,type:'formative',event:e,result})});
  (feedback||[]).forEach(f=>entries.push({date:f.createdAt,type:'feedback',feedback:f}));
  (attendance||[]).forEach(a=>entries.push({date:a.date||a.createdAt,type:'attendance',attendance:a}));
  entries.sort((a,b)=>new Date(b.date)-new Date(a.date));
  const graded=entries.filter(x=>x.type==='formative'&&x.result).length,notes=entries.filter(x=>x.type==='feedback').length,lessons=entries.filter(x=>x.type==='attendance').length;
  return <div className="diary-page"><div className="diary-heading"><div><span className="eyebrow">PROJECT JOURNAL</span><h2>Dienasgrāmata</h2><p>Vienuviet tavs apmeklējums, vērtējumi un skolotāja atgriezeniskā saite.</p></div><div className="diary-stats"><div><b>{lessons}</b><span>Lessons</span></div><div><b>{graded}</b><span>Assessments</span></div><div><b>{notes}</b><span>Feedback</span></div></div></div>{entries.length===0?<section className="panel diary-empty"><BookOpen size={28}/><h3>Dienasgrāmata vēl ir tukša</h3><p>Te parādīsies nodarbības, apmeklējums, formatīvie un skolotāja komentāri.</p></section>:<div className="diary-timeline">{entries.map((x,i)=><DiaryEntry x={x} i={i} key={`${x.type}-${i}`}/>)}</div>}</div>
}
function DiaryEntry({x,i}){
  if(x.type==='attendance'){const status=String(x.attendance.status||'').toLowerCase();const late=status==='late';const absent=['absent','missing','not_present'].includes(status);return <div className="diary-event attendance"><div className="diary-rail"><span className="diary-dot">{absent?<UserX size={16}/>:late?<Clock size={16}/>:<UserCheck size={16}/>}</span></div><article className="diary-card attendance-card"><header className="diary-card-head"><div><span className="diary-type attendance-type"><CalendarDays size={13}/> Lesson attendance</span><h3>{absent?'Absent':late?'Late':'Present'}</h3><div className="diary-date"><CalendarDays size={13}/>{new Date(x.date).toLocaleDateString('lv-LV',{day:'2-digit',month:'long',year:'numeric'})}</div></div><Badge tone={absent?'red':late?'amber':'green'}>{x.attendance.status||'Present'}</Badge></header>{x.attendance.lateMinutes>0&&<div className="attendance-detail">Late by {x.attendance.lateMinutes} min</div>}</article></div>}
  if(x.type==='formative')return <div className="diary-event formative"><div className="diary-rail"><span className="diary-dot"><Award size={16}/></span></div><article className="diary-card"><header className="diary-card-head"><div><span className="diary-type formative-type"><Award size={13}/> Formative assessment</span><h3>{x.event.title}</h3><div className="diary-date"><CalendarDays size={13}/>{new Date(x.event.date).toLocaleDateString('lv-LV',{day:'2-digit',month:'long',year:'numeric'})}</div></div>{x.result?<div className="diary-result"><strong>{x.result.percent}%</strong><span>{x.result.total}/{x.result.maxTotal} points</span></div>:<Badge tone="amber">Awaiting assessment</Badge>}</header>{x.event.description&&<p className="diary-description">{x.event.description}</p>}<div className="diary-scores">{x.event.criteria.map(c=>{const s=x.result?.scores?.find(z=>z.name===c.name);return <div key={c.name}><span>{c.name}</span><b>{s?`${s.score} / ${c.max}`:`— / ${c.max}`}</b>{s&&<Progress value={c.max?s.score/c.max*100:0}/>}</div>})}</div>{x.result&&<div className="diary-review-grid">{x.result.positive&&<div className="diary-note positive"><span><Check size={14}/> What went well</span><p>{x.result.positive}</p></div>}{x.result.improvement&&<div className="diary-note improvement"><span><AlertTriangle size={14}/> Improve next</span><p>{x.result.improvement}</p></div>}{x.result.feedback&&<div className="diary-note general"><span><MessageSquareText size={14}/> Teacher comment</span><p>{x.result.feedback}</p></div>}</div>}</article></div>;
  return <div className="diary-event feedback"><div className="diary-rail"><span className="diary-dot"><MessageSquareText size={16}/></span></div><article className="diary-card"><header className="diary-card-head"><div><span className="diary-type feedback-type"><MessageSquareText size={13}/> Teacher feedback</span><h3>{x.feedback.type==='positive'?'Positive feedback':x.feedback.type==='improvement'?'Improvement note':'Teacher note'}</h3><div className="diary-date"><CalendarDays size={13}/>{new Date(x.feedback.createdAt).toLocaleDateString('lv-LV',{day:'2-digit',month:'long',year:'numeric'})}</div></div></header><div className={`diary-feedback-body ${x.feedback.type||'general'}`}><p>{x.feedback.text}</p></div></article></div>
}

function Assessment({a,user,project,assignment,openCriteria}){const defaults=a?.criteria||(assignment?.rubric||[]).map(x=>({...x,score:0}));const [criteria,setCriteria]=useState(defaults);const [saving,setSaving]=useState(false);const total=criteria.reduce((s,c)=>s+Number(c.score||0),0),max=criteria.reduce((s,c)=>s+Number(c.max||0),0),pct=max?Math.round(total/max*100):0;async function save(){setSaving(true);const r=await fetch('/api/assessments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:a?.id,projectId:project.id,studentId:project.studentId,criteria})});setSaving(false);if(r.ok)location.reload();else alert((await r.json()).error)}return <div className="assessment-layout"><section className="panel assessment-hero"><div><span>Current result</span><strong>{a?.grade??'—'}</strong><small>Grade</small></div><div><span>Points</span><strong>{a?.total??total}/{a?.maxTotal??max}</strong><small>{a?.percent??pct}% of maximum</small></div><Progress value={a?.percent??pct}/><button className="btn secondary wide" onClick={openCriteria}>View full rubric</button></section><section className="panel"><div className="panel-title"><div><h3>Assessment</h3><small>{user.role==='student'?'Your published final assessment.':'Enter final scores for each criterion.'}</small></div>{user.role!=='student'&&<button className="btn primary" onClick={save} disabled={saving}>{saving?'Saving…':'Save assessment'}</button>}</div>{criteria.map((c,i)=><div className="assessment-row" key={c.name}><div><b>{c.name}</b><small>Maximum {c.max} points</small></div>{user.role==='student'?<strong>{c.score}/{c.max}</strong>:<div className="score-input"><input type="number" min="0" max={c.max} value={c.score} onChange={e=>setCriteria(criteria.map((x,j)=>j===i?{...x,score:Math.min(c.max,Math.max(0,Number(e.target.value)))}:x))}/><span>/ {c.max}</span></div>}<Progress value={c.max?c.score/c.max*100:0}/></div>)}</section></div>}
function TeacherTools({review,runReview,busy,feedback,user,project}){return <div className="teacher-tools-grid"><section><div className="teacher-tools-head"><div><h2>Teacher tools</h2><p>Private analysis and feedback are kept away from the student-facing workspace.</p></div><button className="btn primary" onClick={runReview} disabled={busy||!project.githubRepo}><Sparkles size={16}/> Run private review</button></div><Review review={review}/></section><Feedback items={feedback} user={user} project={project}/></div>}
function Review({review}){if(!review)return <div className="panel empty">No private review yet.</div>;const scores=[['Architecture',review.architecture],['Code quality',review.codeQuality],['Security',review.security],['Database',review.database],['Git workflow',review.gitWorkflow],['Documentation',review.documentation]];return <div className="review-grid"><section className="panel"><h3>Private teacher analysis</h3><div className="score-grid">{scores.map(([n,v])=><div key={n}><span>{n}</span><b>{v}/10</b><Progress value={v*10}/></div>)}</div></section><section className="panel"><h3>Findings</h3>{review.positives?.map(x=><p className="review-good" key={x}><Check size={16}/>{x}</p>)}{review.issues?.map(x=><p className="review-issue" key={x.title}><AlertTriangle size={16}/><span>{x.title}</span></p>)}</section></div>}
function Feedback({items,user,project}){const [type,setType]=useState('positive');const [text,setText]=useState('');async function add(){if(text.trim().length<2)return;const r=await fetch('/api/feedback',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({studentId:project.studentId,projectId:project.id,type,text})});if(r.ok)location.reload()}return <><div className="three-col">{['positive','improvement','general'].map(t=><section className="panel" key={t}><h3>{t==='positive'?'Strengths':t==='improvement'?'Needs improvement':'General feedback'}</h3>{items.filter(i=>i.type===t).map(i=><p className="feedback-item" key={i.id}>{i.text}</p>)}</section>)}</div>{user.role!=='student'&&<section className="panel feedback-form"><div className="form-row"><select value={type} onChange={e=>setType(e.target.value)}><option value="positive">Strength</option><option value="improvement">Needs improvement</option><option value="general">General feedback</option></select><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Write feedback…"/><button className="btn primary" onClick={add}>Add feedback</button></div></section>}</>}
function language(path=''){if(path.endsWith('.php'))return 'php';if(path.endsWith('.js')||path.endsWith('.jsx')||path.endsWith('.ts')||path.endsWith('.tsx'))return 'jsx';if(path.endsWith('.json'))return 'json';if(path.endsWith('.md'))return 'markdown';if(path.endsWith('.css')||path.endsWith('.scss'))return 'css';return 'markup'}
