'use client';
import { useMemo,useState } from 'react';
import Link from 'next/link';
import { Sparkles,Github,GitCommitHorizontal,CalendarDays,Check,AlertTriangle,MessageSquareText,Award,Save,RefreshCw,Target,ChevronDown,ExternalLink } from 'lucide-react';

const DEFAULT_PROMPT='Izvērtē studenta projektu pret assignment prasībām un rubriku. Pievērs īpašu uzmanību faktiskajai koda kvalitātei, Git vēsturei, drošībai un tam, vai funkcionalitāte tiešām ir realizēta. Dod konkrētus pierādījumus no koda un īsus, praktiskus secinājumus skolotājam.';

export default function TeacherReviewWorkspace({project,assignment,student,commits=[],feedback=[],assessment,review,formative=[]}){
  const initialCriteria=(assessment?.criteria||(assignment?.rubric||[]).map(c=>({...c,score:0}))).map(c=>({...c,score:Number(c.score||0)}));
  const [criteria,setCriteria]=useState(initialCriteria),[ai,setAi]=useState(review),[aiBusy,setAiBusy]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
  const [prompt,setPrompt]=useState(review?.teacherPrompt||DEFAULT_PROMPT),[feedbackType,setFeedbackType]=useState('general'),[feedbackText,setFeedbackText]=useState('');
  const [mode,setMode]=useState('summative'),[formativeId,setFormativeId]=useState(formative[0]?.id||'');
  const selectedFormative=formative.find(x=>x.id===formativeId)||null;
  const existingFormative=selectedFormative?.results?.find(r=>r.studentId===student.id)||null;
  const [formativeScores,setFormativeScores]=useState(()=>scoresFor(selectedFormative,student.id));
  const [formativeFeedback,setFormativeFeedback]=useState(existingFormative?.feedback||'');
  const total=criteria.reduce((s,c)=>s+Number(c.score||0),0),max=criteria.reduce((s,c)=>s+Number(c.max||0),0),percent=max?Math.round(total/max*100):0;
  const repoConnected=!!project.githubRepo,latestCommit=commits[0];
  const groupedFeedback=useMemo(()=>feedback.slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,5),[feedback]);

  function selectFormative(id){setFormativeId(id);const ev=formative.find(x=>x.id===id);const result=ev?.results?.find(r=>r.studentId===student.id);setFormativeScores(scoresFor(ev,student.id));setFormativeFeedback(result?.feedback||'')}
  async function generateAi(){if(!repoConnected||aiBusy)return;setAiBusy(true);setMessage('');try{const r=await fetch('/api/ai/review',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectId:project.id,prompt})});const d=await r.json();if(!r.ok)throw new Error(d.error||'AI review failed');setAi(d.review);if(!feedbackText.trim()){const parts=[];if(d.review?.positives?.length)parts.push(`Stiprās puses:\n${d.review.positives.slice(0,3).map(x=>`• ${x}`).join('\n')}`);if(d.review?.issues?.length)parts.push(`Uzlabojams:\n${d.review.issues.slice(0,3).map(x=>`• ${x.title||x}`).join('\n')}`);setFeedbackText(parts.join('\n\n'))}setMessage('AI review generated.')}catch(e){setMessage(e.message)}finally{setAiBusy(false)}}
  async function saveFeedback(){if(feedbackText.trim().length<2||saving)return;setSaving(true);setMessage('');try{const r=await fetch('/api/feedback',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({studentId:student.id,projectId:project.id,type:feedbackType,text:feedbackText.trim()})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save feedback');setFeedbackText('');setMessage('Feedback saved.')}catch(e){setMessage(e.message)}finally{setSaving(false)}}
  async function saveAssessment(){if(saving)return;setSaving(true);setMessage('');try{const r=await fetch('/api/assessments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:assessment?.id,projectId:project.id,studentId:student.id,criteria:criteria.map(({name,max,score})=>({name,max,score}))})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save assessment');setMessage(`Assessment saved · grade ${d.item?.grade??gradeFromPercent(percent)}`)}catch(e){setMessage(e.message)}finally{setSaving(false)}}
  async function saveFormative(){if(!selectedFormative||saving)return;setSaving(true);setMessage('');try{const r=await fetch('/api/formative',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'grade',eventId:selectedFormative.id,studentId:student.id,scores:formativeScores,feedback:formativeFeedback})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save formative result');setMessage(`Formative saved · ${d.result?.percent??0}%`)}catch(e){setMessage(e.message)}finally{setSaving(false)}}

  return <div className="review-workspace review-workspace-v2">
    <div className="review-workspace-top"><div><Link className="review-back" href={assignment?`/assignments/${assignment.id}`:'/projects'}>← Back to projects</Link><span className="eyebrow">TEACHER REVIEW</span><h1>{student.firstName} {student.lastName}</h1><p>{project.name}</p></div><div className="review-top-actions">{repoConnected?<a className="btn secondary" target="_blank" rel="noreferrer" href={`https://github.com/${project.githubOwner}/${project.githubRepo}`}><Github size={15}/>{project.githubOwner}/{project.githubRepo}<ExternalLink size={12}/></a>:<span className="review-repo-missing">GitHub not connected</span>}</div></div>
    {message&&<div className="review-message">{message}</div>}

    <div className="review-v2-layout">
      <main className="review-v2-main">
        <section className="review-card review-prompt-card"><div className="review-section-head"><div><span className="eyebrow">AI PROMPT</span><h2>What should AI review?</h2></div><button className="btn primary" disabled={aiBusy||!repoConnected||!prompt.trim()} onClick={generateAi}>{aiBusy?<RefreshCw className="spin" size={15}/>:<Sparkles size={15}/>} {aiBusy?'Reviewing project…':'Generate AI review'}</button></div><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows="5"/><div className="review-prompt-hint">This prompt is private and is sent together with the assignment, rubric, repository files, commits and previous formative history.</div></section>

        <section className="review-ai-stage"><div className="review-section-head"><div><span className="eyebrow">PRIVATE ANALYSIS</span><h2>AI review</h2></div>{ai?.createdAt&&<span className="review-generated-at">Generated {new Date(ai.createdAt).toLocaleString('lv-LV')}</span>}</div><AiReview review={ai}/></section>

        <section className="review-card feedback-compose review-feedback-large"><div className="review-section-head"><div><span className="eyebrow">STUDENT-FACING</span><h2>Feedback</h2></div></div><div className="feedback-type-tabs">{[['positive','Strength'],['improvement','Improve'],['general','General']].map(([v,l])=><button key={v} className={feedbackType===v?'active':''} onClick={()=>setFeedbackType(v)}>{l}</button>)}</div><textarea rows="9" value={feedbackText} onChange={e=>setFeedbackText(e.target.value)} placeholder="Write feedback here, or generate an AI review first and use the prepared draft…"/><div className="review-feedback-actions"><span>Only this text is visible to the student.</span><button className="btn primary" onClick={saveFeedback} disabled={saving||feedbackText.trim().length<2}><MessageSquareText size={15}/> Save feedback</button></div></section>

        {groupedFeedback.length>0&&<details className="review-history"><summary>Previous feedback <ChevronDown size={14}/></summary>{groupedFeedback.map(f=><div key={f.id}><span>{f.type}</span><p>{f.text}</p></div>)}</details>}
      </main>

      <aside className="review-v2-sidebar">
        <section className="review-card review-sidebar-assessment"><div className="review-section-head"><div><span className="eyebrow">ASSESSMENT</span><h2>Rubric</h2></div></div><div className="assessment-mode"><button className={mode==='summative'?'active':''} onClick={()=>setMode('summative')}>Summative</button><button className={mode==='formative'?'active':''} onClick={()=>setMode('formative')}>Formative</button></div>{mode==='summative'?<><div className="grade-result"><div><span>Points</span><b>{total}<small>/{max}</small></b></div><div><span>Percent</span><b>{percent}%</b></div><div><span>Grade</span><b>{gradeFromPercent(percent)}</b></div></div><div className="sidebar-rubric-list">{criteria.map((c,i)=><label className="quick-score" key={`${c.name}-${i}`}><div><b>{c.name}</b><span>max {c.max}</span></div><div><input type="number" min="0" max={c.max} value={c.score} onChange={e=>setCriteria(criteria.map((x,j)=>j===i?{...x,score:Math.min(Number(c.max),Math.max(0,Number(e.target.value)||0))}:x))}/><span>/ {c.max}</span></div></label>)}</div><button className="btn primary wide review-save" disabled={saving||!criteria.length} onClick={saveAssessment}><Save size={15}/> Save assessment</button></>:<FormativePanel events={formative} selected={selectedFormative} selectedId={formativeId} select={selectFormative} scores={formativeScores} setScores={setFormativeScores} feedback={formativeFeedback} setFeedback={setFormativeFeedback} save={saveFormative} saving={saving}/>}</section>

        <section className="review-card review-evidence-card"><div className="review-section-head"><div><span className="eyebrow">PROJECT</span><h2>Evidence</h2></div></div><div className="review-evidence-facts"><div><span>Commits</span><b>{commits.length}</b></div><div><span>Latest</span><b>{latestCommit?new Date(latestCommit.timestamp).toLocaleDateString('lv-LV'):'—'}</b></div><div><span>Deadline</span><b>{assignment?.deadline||project.deadline||'—'}</b></div></div><div className="repo-card-head"><Github size={17}/><div><b>{repoConnected?project.githubRepo:'No repository'}</b><span>{repoConnected?project.githubOwner:'Student has not linked GitHub'}</span></div></div>{assignment?.requirements?.length>0&&<div className="review-sidebar-block"><h3>Requirements</h3><ul className="review-requirements">{assignment.requirements.map(x=><li key={x}>{x}</li>)}</ul></div>}<div className="review-sidebar-block"><h3>Recent commits</h3><div className="review-commit-list">{commits.slice(0,6).map(c=><div key={c.sha}><GitCommitHorizontal size={13}/><div><b>{c.message?.split('\n')[0]||'Commit'}</b><span>{c.author} · {new Date(c.timestamp).toLocaleDateString('lv-LV')}</span></div><code>{c.sha.slice(0,7)}</code></div>)}{!commits.length&&<p className="review-empty">No commit history yet.</p>}</div></div></section>
      </aside>
    </div>
  </div>;
}

function AiReview({review}){if(!review)return <div className="review-card ai-empty ai-empty-large"><Sparkles size={28}/><h3>No AI review yet</h3><p>Edit the prompt above and generate a review. The analysis stays private to the teacher.</p></div>;const scores=[['Architecture',review.architecture],['Code quality',review.codeQuality],['Security',review.security],['Database',review.database],['Git workflow',review.gitWorkflow],['Documentation',review.documentation]];return <div className="review-card ai-review ai-review-large"><div className="ai-score-row">{scores.map(([name,value])=><div key={name}><span>{name}</span><b>{value??'—'}<small>/10</small></b></div>)}</div><div className="ai-review-columns">{review.positives?.length>0&&<div className="ai-findings good"><h4><Check size={14}/> Strengths</h4>{review.positives.map((x,i)=><p key={i}>{x}</p>)}</div>}{review.issues?.length>0&&<div className="ai-findings issues"><h4><AlertTriangle size={14}/> Issues</h4>{review.issues.map((x,i)=><p key={i}><b>{x.title||x}</b>{x.file&&<span>{x.file}{x.line?`:${x.line}`:''}</span>}</p>)}</div>}</div>{review.rubricEvidence?.length>0&&<div className="ai-rubric-evidence"><h4><Target size={14}/> Rubric evidence</h4>{review.rubricEvidence.map((x,i)=><div key={i}><b>{x.criterion}</b><p>{x.evidence}</p><span>AI suggestion: {x.suggestedScore}</span></div>)}</div>}{review.recommendations?.length>0&&<div className="ai-recommendations"><h4>Recommendations</h4>{review.recommendations.map((x,i)=><p key={i}>• {x}</p>)}</div>}</div>}
function FormativePanel({events,selected,selectedId,select,scores,setScores,feedback,setFeedback,save,saving}){if(!events.length)return <div className="ai-empty"><Award size={22}/><h3>No formative assessments</h3><p>Create one for this assignment first.</p></div>;const total=scores.reduce((s,x)=>s+Number(x.score||0),0),max=scores.reduce((s,x)=>s+Number(x.max||0),0);return <div className="formative-quick"><label><span>Assessment</span><select value={selectedId} onChange={e=>select(e.target.value)}>{events.map(e=><option key={e.id} value={e.id}>{e.title} · {e.date}</option>)}</select></label>{selected?.criteria?.map((c,i)=><label className="quick-score" key={c.name}><div><b>{c.name}</b><span>max {c.max}</span></div><div><input type="number" min="0" max={c.max} value={scores.find(x=>x.name===c.name)?.score??0} onChange={e=>setScores(scores.map((x,j)=>j===i?{...x,score:Math.min(Number(c.max),Math.max(0,Number(e.target.value)||0))}:x))}/><span>/ {c.max}</span></div></label>)}<div className="formative-total"><span>Quick result</span><b>{max?Math.round(total/max*100):0}%</b></div><textarea rows="4" value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="Short formative feedback…"/><button className="btn primary wide review-save" onClick={save} disabled={saving||!selected}><Save size={15}/> Save formative</button></div>}
function scoresFor(event,studentId){if(!event)return[];const result=event.results?.find(r=>r.studentId===studentId);return (event.criteria||[]).map(c=>({name:c.name,max:Number(c.max),score:Number(result?.scores?.find(x=>x.name===c.name)?.score||0)}))}
function gradeFromPercent(p){if(p>=90)return 10;if(p>=80)return 9;if(p>=70)return 8;if(p>=60)return 7;if(p>=50)return 6;if(p>=40)return 5;if(p>=30)return 4;if(p>=20)return 3;if(p>=10)return 2;return 1}
