'use client';
import { useMemo,useState } from 'react';
import Link from 'next/link';
import { Sparkles,Github,GitCommitHorizontal,Check,AlertTriangle,MessageSquareText,Award,Save,RefreshCw,Target,ChevronDown,ExternalLink,Flag } from 'lucide-react';
import { gradeFromPercent } from '@/lib/grading';

const DEFAULT_PROMPT='Izvērtē studenta projektu pret assignment prasībām un rubriku. Pievērs īpašu uzmanību faktiskajai koda kvalitātei, Git vēsturei, drošībai un tam, vai funkcionalitāte tiešām ir realizēta. Dod konkrētus pierādījumus no koda un īsus, praktiskus secinājumus skolotājam.';

export default function TeacherReviewWorkspace({project,assignment,student,commits=[],feedback=[],assessment,review,formative=[],summative=[]}){
  const [ai,setAi]=useState(review),[aiBusy,setAiBusy]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
  const [prompt,setPrompt]=useState(review?.teacherPrompt||DEFAULT_PROMPT),[feedbackType,setFeedbackType]=useState('general'),[feedbackText,setFeedbackText]=useState('');
  const [mode,setMode]=useState(summative.length?'summative':formative.length?'formative':'final');
  const [summativeId,setSummativeId]=useState(summative[0]?.id||''),[formativeId,setFormativeId]=useState(formative[0]?.id||'');
  const selectedSummative=summative.find(x=>x.id===summativeId)||null,selectedFormative=formative.find(x=>x.id===formativeId)||null;
  const [summativeScores,setSummativeScores]=useState(()=>scoresFor(selectedSummative,student.id));
  const [summativeFeedback,setSummativeFeedback]=useState(()=>resultFor(selectedSummative,student.id)?.feedback||'');
  const [formativeScores,setFormativeScores]=useState(()=>scoresFor(selectedFormative,student.id));
  const [formativeFeedback,setFormativeFeedback]=useState(()=>resultFor(selectedFormative,student.id)?.feedback||'');
  const [finalGrade,setFinalGrade]=useState(assessment?.grade?String(assessment.grade):'');
  const repoConnected=!!project.githubRepo,latestCommit=commits[0];
  const groupedFeedback=useMemo(()=>feedback.slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,5),[feedback]);

  function selectSummative(id){setSummativeId(id);const ev=summative.find(x=>x.id===id);setSummativeScores(scoresFor(ev,student.id));setSummativeFeedback(resultFor(ev,student.id)?.feedback||'')}
  function selectFormative(id){setFormativeId(id);const ev=formative.find(x=>x.id===id);setFormativeScores(scoresFor(ev,student.id));setFormativeFeedback(resultFor(ev,student.id)?.feedback||'')}
  async function generateAi(){if(!repoConnected||aiBusy)return;setAiBusy(true);setMessage('');try{const r=await fetch('/api/ai/review',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectId:project.id,prompt})});const d=await r.json();if(!r.ok)throw new Error(d.error||'AI review failed');setAi(d.review);if(!feedbackText.trim()){const parts=[];if(d.review?.positives?.length)parts.push(`Stiprās puses:\n${d.review.positives.slice(0,3).map(x=>`• ${x}`).join('\n')}`);if(d.review?.issues?.length)parts.push(`Uzlabojams:\n${d.review.issues.slice(0,3).map(x=>`• ${x.title||x}`).join('\n')}`);setFeedbackText(parts.join('\n\n'))}setMessage('AI review generated.')}catch(e){setMessage(e.message)}finally{setAiBusy(false)}}
  async function saveFeedback(){if(feedbackText.trim().length<2||saving)return;setSaving(true);setMessage('');try{const r=await fetch('/api/feedback',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({studentId:student.id,projectId:project.id,type:feedbackType,text:feedbackText.trim()})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save feedback');setFeedbackText('');setMessage('Feedback saved.')}catch(e){setMessage(e.message)}finally{setSaving(false)}}
  async function saveSummative(){if(!selectedSummative||saving)return;setSaving(true);setMessage('');try{const r=await fetch('/api/summative',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'grade',eventId:selectedSummative.id,studentId:student.id,scores:summativeScores,feedback:summativeFeedback})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save summative');setMessage(`${selectedSummative.title} saved · grade ${d.result?.grade??'—'} (${d.result?.percent??0}%)`)}catch(e){setMessage(e.message)}finally{setSaving(false)}}
  async function saveFormative(){if(!selectedFormative||saving)return;setSaving(true);setMessage('');try{const r=await fetch('/api/formative',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'grade',eventId:selectedFormative.id,studentId:student.id,scores:formativeScores,feedback:formativeFeedback})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save formative result');setMessage(`${selectedFormative.title} saved · ${d.result?.percent??0}%`)}catch(e){setMessage(e.message)}finally{setSaving(false)}}
  async function saveFinalGrade(){const grade=Number(finalGrade);if(saving||grade<1||grade>10)return;setSaving(true);setMessage('');try{const r=await fetch('/api/assessments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:assessment?.id,projectId:project.id,studentId:student.id,manualGrade:grade})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save final grade');setFinalGrade(String(d.item?.grade??grade));setMessage(`Final grade saved · ${d.item?.grade??grade}`)}catch(e){setMessage(e.message)}finally{setSaving(false)}}

  return <div className="review-workspace review-workspace-v2">
    <div className="review-workspace-top"><div><Link className="review-back" href={assignment?`/assignments/${assignment.id}`:'/projects'}>← Back to projects</Link><span className="eyebrow">TEACHER REVIEW</span><h1>{student.firstName} {student.lastName}</h1><p>{project.name}</p></div><div className="review-top-actions">{repoConnected?<a className="btn secondary" target="_blank" rel="noreferrer" href={`https://github.com/${project.githubOwner}/${project.githubRepo}`}><Github size={15}/>{project.githubOwner}/{project.githubRepo}<ExternalLink size={12}/></a>:<span className="review-repo-missing">GitHub not connected</span>}</div></div>
    {message&&<div className="review-message">{message}</div>}
    <div className="review-v2-layout">
      <main className="review-v2-main">
        <section className="review-card review-prompt-card"><div className="review-section-head"><div><span className="eyebrow">AI PROMPT</span><h2>What should AI review?</h2></div><button className="btn primary" disabled={aiBusy||!repoConnected||!prompt.trim()} onClick={generateAi}>{aiBusy?<RefreshCw className="spin" size={15}/>:<Sparkles size={15}/>} {aiBusy?'Reviewing project…':'Generate AI review'}</button></div><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows="5"/><div className="review-prompt-hint">This prompt is private and is sent together with the assignment, rubric, repository files, commits and previous assessment history.</div></section>
        <section className="review-ai-stage"><div className="review-section-head"><div><span className="eyebrow">PRIVATE ANALYSIS</span><h2>AI review</h2></div>{ai?.createdAt&&<span className="review-generated-at">Generated {new Date(ai.createdAt).toLocaleString('lv-LV')}</span>}</div><AiReview review={ai}/></section>
        <section className="review-card feedback-compose review-feedback-large"><div className="review-section-head"><div><span className="eyebrow">STUDENT-FACING</span><h2>Feedback</h2></div></div><div className="feedback-type-tabs">{[['positive','Strength'],['improvement','Improve'],['general','General']].map(([v,l])=><button key={v} className={feedbackType===v?'active':''} onClick={()=>setFeedbackType(v)}>{l}</button>)}</div><textarea rows="9" value={feedbackText} onChange={e=>setFeedbackText(e.target.value)} placeholder="Write feedback here, or generate an AI review first and use the prepared draft…"/><div className="review-feedback-actions"><span>Only this text is visible to the student.</span><button className="btn primary" onClick={saveFeedback} disabled={saving||feedbackText.trim().length<2}><MessageSquareText size={15}/> Save feedback</button></div></section>
        {groupedFeedback.length>0&&<details className="review-history"><summary>Previous feedback <ChevronDown size={14}/></summary>{groupedFeedback.map(f=><div key={f.id}><span>{f.type}</span><p>{f.text}</p></div>)}</details>}
      </main>
      <aside className="review-v2-sidebar">
        <section className="review-card review-sidebar-assessment"><div className="review-section-head"><div><span className="eyebrow">ASSESSMENT</span><h2>Grading</h2></div></div><div className="assessment-mode assessment-mode-three"><button className={mode==='summative'?'active':''} onClick={()=>setMode('summative')}>Summative <i>{summative.length}</i></button><button className={mode==='formative'?'active':''} onClick={()=>setMode('formative')}>Formative <i>{formative.length}</i></button><button className={mode==='final'?'active':''} onClick={()=>setMode('final')}>Final</button></div>
          {mode==='summative'&&<EventPanel type="summative" events={summative} selected={selectedSummative} selectedId={summativeId} select={selectSummative} scores={summativeScores} setScores={setSummativeScores} feedback={summativeFeedback} setFeedback={setSummativeFeedback} save={saveSummative} saving={saving} studentId={student.id}/>} 
          {mode==='formative'&&<EventPanel type="formative" events={formative} selected={selectedFormative} selectedId={formativeId} select={selectFormative} scores={formativeScores} setScores={setFormativeScores} feedback={formativeFeedback} setFeedback={setFormativeFeedback} save={saveFormative} saving={saving} studentId={student.id}/>} 
          {mode==='final'&&<FinalGradePanel value={finalGrade} setValue={setFinalGrade} assessment={assessment} save={saveFinalGrade} saving={saving}/>} 
        </section>
        <section className="review-card review-evidence-card"><div className="review-section-head"><div><span className="eyebrow">PROJECT</span><h2>Evidence</h2></div></div><div className="review-evidence-facts"><div><span>Commits</span><b>{commits.length}</b></div><div><span>Latest</span><b>{latestCommit?new Date(latestCommit.timestamp).toLocaleDateString('lv-LV'):'—'}</b></div><div><span>Deadline</span><b>{assignment?.deadline||project.deadline||'—'}</b></div></div><div className="repo-card-head"><Github size={17}/><div><b>{repoConnected?project.githubRepo:'No repository'}</b><span>{repoConnected?project.githubOwner:'Student has not linked GitHub'}</span></div></div>{assignment?.requirements?.length>0&&<div className="review-sidebar-block"><h3>Requirements</h3><ul className="review-requirements">{assignment.requirements.map(x=><li key={x}>{x}</li>)}</ul></div>}<div className="review-sidebar-block"><h3>Recent commits</h3><div className="review-commit-list">{commits.slice(0,6).map(c=><div key={c.sha}><GitCommitHorizontal size={13}/><div><b>{c.message?.split('\n')[0]||'Commit'}</b><span>{c.author} · {new Date(c.timestamp).toLocaleDateString('lv-LV')}</span></div><code>{c.sha.slice(0,7)}</code></div>)}{!commits.length&&<p className="review-empty">No commit history yet.</p>}</div></div></section>
      </aside>
    </div>
  </div>;
}

function EventPanel({type,events,selected,selectedId,select,scores,setScores,feedback,setFeedback,save,saving,studentId}){
  if(!events.length)return <div className="ai-empty sidebar-empty"><Award size={22}/><h3>No {type} assessments</h3><p>Add one from the assignment overview first.</p></div>;
  const total=scores.reduce((s,x)=>s+Number(x.score||0),0),max=scores.reduce((s,x)=>s+Number(x.max||0),0),percent=max?Math.round(total/max*100):0;
  const previous=resultFor(selected,studentId);
  return <div className="grading-event-panel"><label className="grading-event-select"><span>{type==='summative'?'Summative assessment':'Formative assessment'}</span><select value={selectedId} onChange={e=>select(e.target.value)}>{events.map((e,i)=><option key={e.id} value={e.id}>{i+1}. {e.title} · {e.date}{resultFor(e,studentId)?' ✓':''}</option>)}</select></label><div className="grading-event-meta"><span>{selected?.date}</span>{previous&&<span className="graded-badge">Saved</span>}</div><div className="grade-result"><div><span>Points</span><b>{total}<small>/{max}</small></b></div><div><span>Percent</span><b>{percent}%</b></div>{type==='summative'&&<div><span>Grade</span><b>{gradeFromPercent(percent)}</b></div>}</div><div className="sidebar-rubric-list">{(selected?.criteria||[]).map((c,i)=><label className="quick-score" key={`${c.name}-${i}`}><div><b>{c.name}</b><span>max {c.max}</span></div><div><input type="number" min="0" max={c.max} value={scores[i]?.score??0} onChange={e=>setScores(scores.map((x,j)=>j===i?{...x,score:Math.min(Number(c.max),Math.max(0,Number(e.target.value)||0))}:x))}/><span>/ {c.max}</span></div></label>)}</div><textarea className="grading-event-feedback" rows="4" value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder={`Feedback for this ${type}…`}/><button className="btn primary wide review-save" onClick={save} disabled={saving||!selected}><Save size={15}/> Save {type}</button></div>
}

function FinalGradePanel({value,setValue,assessment,save,saving}){return <div className="final-grade-panel"><div className="final-grade-current"><Flag size={20}/><div><span>Project final grade</span><b>{assessment?.grade??'Not set'}</b></div></div><p>This is the one final project grade you transfer to e-klase. Summative and formative results stay separate.</p><label><span>Final grade (1–10)</span><input type="number" min="1" max="10" step="1" value={value} onChange={e=>setValue(e.target.value.replace(/\D/g,'').slice(0,2))} placeholder="1–10"/></label><button className="btn primary wide" disabled={saving||Number(value)<1||Number(value)>10} onClick={save}><Save size={15}/> Save final grade</button></div>}

function AiReview({review}){if(!review)return <div className="review-card ai-empty ai-empty-large"><Sparkles size={28}/><h3>No AI review yet</h3><p>Edit the prompt above and generate a review. The analysis stays private to the teacher.</p></div>;const scores=[['Architecture',review.architecture],['Code quality',review.codeQuality],['Security',review.security],['Database',review.database],['Git workflow',review.gitWorkflow],['Documentation',review.documentation]];return <div className="review-card ai-review ai-review-large"><div className="ai-score-row">{scores.map(([name,value])=><div key={name}><span>{name}</span><b>{value??'—'}<small>/10</small></b></div>)}</div><div className="ai-review-columns">{review.positives?.length>0&&<div className="ai-findings good"><h4><Check size={14}/> Strengths</h4>{review.positives.map((x,i)=><p key={i}>{x}</p>)}</div>}{review.issues?.length>0&&<div className="ai-findings issues"><h4><AlertTriangle size={14}/> Issues</h4>{review.issues.map((x,i)=><p key={i}><b>{x.title||x}</b>{x.file&&<span>{x.file}{x.line?`:${x.line}`:''}</span>}</p>)}</div>}</div>{review.rubricEvidence?.length>0&&<div className="ai-rubric-evidence"><h4><Target size={14}/> Rubric evidence</h4>{review.rubricEvidence.map((x,i)=><div key={i}><b>{x.criterion}</b><p>{x.evidence}</p><span>AI suggestion: {x.suggestedScore}</span></div>)}</div>}{review.recommendations?.length>0&&<div className="ai-recommendations"><h4>Recommendations</h4>{review.recommendations.map((x,i)=><p key={i}>• {x}</p>)}</div>}</div>}
function resultFor(event,studentId){return event?.results?.find(r=>r.studentId===studentId)||null}
function scoresFor(event,studentId){if(!event)return[];const result=resultFor(event,studentId);return (event.criteria||[]).map(c=>({name:c.name,max:Number(c.max),score:Number(result?.scores?.find(x=>x.name===c.name)?.score||0)}))}
