import { z } from 'zod';
import { requireApiUser, fail, ok } from '@/lib/http';
import { getUsers } from '@/services/users';
import { getSpotifyAccount,spotifyQueue } from '@/services/spotify';
import { MUSIC_RULES,MUSIC_RULES_VERSION,acceptMusicRules,addMusicRequest,banMusicStudent,getMusicAccess,getMusicAccessList,getMusicQueue,getMusicSettings,moderateMusicRequest,payMusicFine,removeMusicRequest,setMusicRequestsEnabled,unbanMusicStudent } from '@/services/music';
const requestSchema=z.object({action:z.literal('request'),title:z.string().min(1),artist:z.string().optional().default(''),spotifyUrl:z.string().optional().default(''),spotifyId:z.string().optional().default(''),spotifyUri:z.string().optional().default(''),image:z.string().optional().default(''),durationMs:z.coerce.number().optional().default(0),explicit:z.boolean().optional().default(false)});
const actionSchema=z.union([z.object({action:z.literal('accept_rules')}),requestSchema,z.object({action:z.literal('remove_request'),requestId:z.string()}),z.object({action:z.literal('moderate_request'),requestId:z.string(),status:z.enum(['approved','queued','played','removed'])}),z.object({action:z.literal('toggle_requests'),enabled:z.boolean()}),z.object({action:z.literal('ban_student'),studentId:z.string(),durationMinutes:z.coerce.number().positive(),reason:z.string().min(1),severity:z.enum(['low','medium','high']).default('medium'),fine:z.coerce.number().min(0).default(500)}),z.object({action:z.literal('unban_student'),studentId:z.string()}),z.object({action:z.literal('pay_fine')})]);
export async function GET(){const auth=await requireApiUser(['student','teacher','admin']);if(auth.error)return auth.error;try{const [settings,queue,users]=await Promise.all([getMusicSettings(),getMusicQueue(),getUsers()]);let spotifyOwner=null;for(const u of users.filter(x=>['teacher','admin'].includes(x.role))){if(await getSpotifyAccount(u.id)){spotifyOwner=u;break}}const payload={settings:{...settings,spotifyConnected:!!spotifyOwner},queue,rules:MUSIC_RULES,rulesVersion:MUSIC_RULES_VERSION};if(auth.user.role==='student')payload.access=await getMusicAccess(auth.user.id);else{const access=await getMusicAccessList();payload.students=users.filter(u=>u.role==='student').map(s=>({id:s.id,name:`${s.firstName} ${s.lastName}`,email:s.email,access:access.find(a=>a.studentId===s.id)||null}));payload.spotifyConnected=!!(await getSpotifyAccount(auth.user.id));}return ok(payload)}catch(e){return fail(e.message||'Could not load Classroom Music',500)}}
export async function POST(req){const auth=await requireApiUser(['student','teacher','admin']);if(auth.error)return auth.error;try{const body=actionSchema.parse(await req.json());let result;switch(body.action){case'accept_rules':if(auth.user.role!=='student')throw new Error('Student action only');result=await acceptMusicRules(auth.user.id);break;case'request':if(auth.user.role!=='student')throw new Error('Student action only');result=await addMusicRequest(auth.user,body);break;case'remove_request':result=await removeMusicRequest(body.requestId,auth.user);break;case'moderate_request':result=await moderateMusicRequest(body.requestId,body.status,auth.user);if(body.status==='queued'&&result.spotifyUri)await spotifyQueue(auth.user.id,result.spotifyUri);break;case'toggle_requests':result=await setMusicRequestsEnabled(body.enabled,auth.user);break;case'ban_student':result=await banMusicStudent(body.studentId,body,auth.user);break;case'unban_student':result=await unbanMusicStudent(body.studentId,auth.user);break;case'pay_fine':if(auth.user.role!=='student')throw new Error('Student action only');result=await payMusicFine(auth.user.id);break}return ok({result})}catch(e){return fail(e.message||'Music action failed',400,e?.issues)}}
